DELETE FROM banned_club;

INSERT INTO banned_club (name)
VALUES
    ('10'),
    ('10y'),
    ('10 year old'),
    ('10 year-old'),
    ('10-year-old'),
    ('10 years'),
    ('10years'),
    ('10 years old'),
    ('10 yo'),
    ('10yo'),
    ('11 year old'),
    ('11 year-old'),
    ('11-year-old'),
    ('11 years old'),
    ('12'),
    ('12y'),
    ('12 year old'),
    ('12 year-old'),
    ('12-year-old'),
    ('12 years'),
    ('12years'),
    ('12 years old'),
    ('12 yo'),
    ('12yo'),
    ('13'),
    ('13y'),
    ('13 year old'),
    ('13 year-old'),
    ('13-year-old'),
    ('13 years'),
    ('13years'),
    ('13 years old'),
    ('13 yo'),
    ('13yo'),
    ('14'),
    ('1488'),
    ('14y'),
    ('14 year old'),
    ('14 year-old'),
    ('14-year-old'),
    ('14 years'),
    ('14years'),
    ('14 years old'),
    ('14 yo'),
    ('14yo'),
    ('15'),
    ('15y'),
    ('15 year old'),
    ('15 year-old'),
    ('15-year-old'),
    ('15 years'),
    ('15years'),
    ('15 years old'),
    ('15 yo'),
    ('15yo'),
    ('16'),
    ('16y'),
    ('16 year old'),
    ('16 year-old'),
    ('16-year-old'),
    ('16 years'),
    ('16years'),
    ('16 years old'),
    ('16 yo'),
    ('16yo'),
    ('17'),
    ('17y'),
    ('17 year old'),
    ('17 year-old'),
    ('17-year-old'),
    ('17 years'),
    ('17years'),
    ('17 years old'),
    ('17 yo'),
    ('17yo'),
    ('18'),
    ('311'),
    ('38'),
    ('4chan is for faggots'),
    ('5'),
    ('50 suicide attempts'),
    ('5y'),
    ('5 year old'),
    ('5 year-old'),
    ('5-year-old'),
    ('5 years'),
    ('5years'),
    ('5 years old'),
    ('5 yo'),
    ('5yo'),
    ('6'),
    ('6y'),
    ('6 year old'),
    ('6 year-old'),
    ('6-year-old'),
    ('6 years'),
    ('6years'),
    ('6 years old'),
    ('6 yo'),
    ('6yo'),
    ('7'),
    ('7y'),
    ('7 year old'),
    ('7 year-old'),
    ('7-year-old'),
    ('7 years'),
    ('7years'),
    ('7 years old'),
    ('7 yo'),
    ('7yo'),
    ('8'),
    ('88'),
    ('8y'),
    ('8 year old'),
    ('8 year-old'),
    ('8-year-old'),
    ('8 years'),
    ('8years'),
    ('8 years old'),
    ('8 yo'),
    ('8yo'),
    ('9'),
    ('9y'),
    ('9 year old'),
    ('9 year-old'),
    ('9-year-old'),
    ('9 years'),
    ('9years'),
    ('9 years old'),
    ('9 yo'),
    ('9yo'),
    ('a10 aryan'),
    ('abuse me'),
    ('abuser'),
    ('abusive'),
    ('adolf hitler'),
    ('age gap'),
    ('age play'),
    ('agere'),
    ('age regress'),
    ('age regressor'),
    ('allah akbar'),
    ('allah is a jew'),
    ('allahu akbar'),
    ('alt faggot'),
    ('among us rape'),
    ('amongusrape'),
    ('animal abuse'),
    ('anti asians'),
    ('anti-asians'),
    ('anti black people'),
    ('anti-black people'),
    ('anti blacks'),
    ('anti-blacks'),
    ('anti-blm'),
    ('anti british'),
    ('anti brown people'),
    ('anti-brown people'),
    ('anti buddhists'),
    ('anti-buddhists'),
    ('anti bug people'),
    ('anti-bug people'),
    ('anti bugs'),
    ('anti-bugs'),
    ('anti chinks'),
    ('anti-chinks'),
    ('anti christianity'),
    ('anti-christianity'),
    ('anti christians'),
    ('anti-christians'),
    ('anti coons'),
    ('anti-coons'),
    ('anti-faggotry'),
    ('anti faggots'),
    ('anti-faggots'),
    ('anti fags'),
    ('anti-fags'),
    ('anti feminist'),
    ('anti filipinas'),
    ('anti-filipinas'),
    ('anti filipino people'),
    ('anti-filipino people'),
    ('anti filipinos'),
    ('anti-filipinos'),
    ('anti flips'),
    ('anti-flips'),
    ('anti french'),
    ('anti-gay'),
    ('anti gays'),
    ('anti-gays'),
    ('anti hinduim'),
    ('anti-hinduim'),
    ('anti hindus'),
    ('anti-hindus'),
    ('anti india'),
    ('anti-india'),
    ('anti indians'),
    ('anti-indians'),
    ('anti irish "people"'),
    ('anti irish people'),
    ('anti-irish "people"'),
    ('anti-irish people'),
    ('anti islam'),
    ('anti-islam'),
    ('anti israel'),
    ('anti-israel'),
    ('anti jewish people'),
    ('anti-jewish people'),
    ('anti jews'),
    ('anti-jews'),
    ('anti judaism'),
    ('anti-judaism'),
    ('anti kikes'),
    ('anti-kikes'),
    ('anti latinos'),
    ('anti-latinos'),
    ('anti lgbtq'),
    ('anti-lgbtq'),
    ('anti-lgbtqiap'),
    ('anti loli'),
    ('anti-loli'),
    ('anti men'),
    ('anti-men'),
    ('anti mexicans'),
    ('anti-mexicans'),
    ('anti minorities'),
    ('anti-minorities'),
    ('anti mormons'),
    ('anti-mormons'),
    ('anti muslims'),
    ('anti-muslims'),
    ('anti my faggot life'),
    ('anti-my faggot life'),
    ('anti nazis'),
    ('anti-nazis'),
    ('anti niggers'),
    ('anti-niggers'),
    ('anti nigs'),
    ('anti-nigs'),
    ('anti norway'),
    ('anti-norway'),
    ('anti pakis'),
    ('anti-pakis'),
    ('anti palestine'),
    ('anti-palestine'),
    ('anti quebec'),
    ('anti-quebec'),
    ('anti queers'),
    ('anti-queers'),
    ('anti retard retard club'),
    ('anti-semetic zionist'),
    ('antisemit'),
    ('antisemita'),
    ('antisemitas'),
    ('anti semite'),
    ('anti-semite'),
    ('antisemite'),
    ('antisemiten'),
    ('antisemiti'),
    ('anti semitic'),
    ('anti-semitic'),
    ('antisemitic'),
    ('antisemitin'),
    ('antisemitinnen'),
    ('anti semitism'),
    ('anti-semitism'),
    ('antisemitism'),
    ('antisemitismo'),
    ('antissemita'),
    ('antissemitas'),
    ('anti the fags'),
    ('anti-the fags'),
    ('anti trannies'),
    ('anti-trannies'),
    ('anti-trans'),
    ('anti white people'),
    ('anti-white people'),
    ('anti whites'),
    ('anti-whites'),
    ('anti-wog'),
    ('anti women'),
    ('anti-women'),
    ('anti-zionist'),
    ('are you hanging yourself'),
    ('aryan'),
    ('aryan emperor'),
    ('aryan jihad'),
    ('aryans'),
    ('aryanx'),
    ('asian beater'),
    ('asian hater'),
    ('asians hater'),
    ('assbeater420'),
    ('assisted suicide'),
    ('autistic fag boyfriend'),
    ('autistic faggot'),
    ('azur lane faggot'),
    ('beaner'),
    ('beating up minorities'),
    ('beat me to death'),
    ('bestiality'),
    ('biblically accurate misandrist'),
    ('billions must die'),
    ('black hater'),
    ('black people beater'),
    ('black people hater'),
    ('blacks hater'),
    ('bnwo'),
    ('boykisser'),
    ('boy rapist'),
    ('brown people beater'),
    ('brown people hater'),
    ('brown racist'),
    ('buddhists hater'),
    ('bug beater'),
    ('bug hater'),
    ('bug killer'),
    ('bug people beater'),
    ('bug people hater'),
    ('bugs hater'),
    ('buying drugs'),
    ('buy me valorant skins'),
    ('certified minor'),
    ('child abuse'),
    ('child lover'),
    ('child porn'),
    ('child rape'),
    ('childrape'),
    ('child rapist'),
    ('child trafficker'),
    ('child traficker'),
    ('chill pedo vibes'),
    ('chink'),
    ('chink beater'),
    ('chink hater'),
    ('chinks'),
    ('chinks hater'),
    ('christian hater'),
    ('christianity hater'),
    ('christians hater'),
    ('coal burner'),
    ('coalburner'),
    ('coal burners'),
    ('coalburners'),
    ('consensual rape'),
    ('consensualrape'),
    ('contradictory faggot'),
    ('coon'),
    ('coon hater'),
    ('coons'),
    ('coons hater'),
    ('cotton picker'),
    ('cunny'),
    ('cunny archive'),
    ('cunnyborea'),
    ('cunny cumdump'),
    ('cunnymaxxing'),
    ('cunny rape'),
    ('cunnyrape'),
    ('cunnyseur'),
    ('cuny'),
    ('cute and funny'),
    ('cut me'),
    ('cutter'),
    ('cutting'),
    ('death to america'),
    ('death to israel'),
    ('deport asians'),
    ('deport black people'),
    ('deport blacks'),
    ('deport brown people'),
    ('deport buddhists'),
    ('deport bug people'),
    ('deport bugs'),
    ('deport chinks'),
    ('deport christianity'),
    ('deport christians'),
    ('deport coons'),
    ('deport faggots'),
    ('deport fags'),
    ('deport filipinas'),
    ('deport filipino people'),
    ('deport filipinos'),
    ('deport flips'),
    ('deport gays'),
    ('deport hinduim'),
    ('deport hindus'),
    ('deport india'),
    ('deport indians'),
    ('deport irish "people"'),
    ('deport irish people'),
    ('deport islam'),
    ('deport israel'),
    ('deport jewish people'),
    ('deport jews'),
    ('deport judaism'),
    ('deport kikes'),
    ('deport latinos'),
    ('deport lgbtq'),
    ('deport loli'),
    ('deport men'),
    ('deport mexicans'),
    ('deport minorities'),
    ('deport mormons'),
    ('deport muslims'),
    ('deport my faggot life'),
    ('deport nazis'),
    ('deport niggers'),
    ('deport nigs'),
    ('deport norway'),
    ('deport pakis'),
    ('deport palestine'),
    ('deport quebec'),
    ('deport queers'),
    ('deport the fags'),
    ('deport trannies'),
    ('deport white people'),
    ('deport whites'),
    ('deport women'),
    ('die nazis die'),
    ('die retard die'),
    ('domestic abuse'),
    ('domestic terrorist'),
    ('don''t be trans'),
    ('dothead'),
    ('drug abuser'),
    ('drugabuser'),
    ('drug addict'),
    ('drug addicts'),
    ('drug cartel'),
    ('drug dealer'),
    ('druggo'),
    ('drug me'),
    ('drugs'),
    ('dukys'),
    ('edtwt users kys'),
    ('eight year old'),
    ('eight year-old'),
    ('eight-year-old'),
    ('eight years old'),
    ('eight yo'),
    ('eleven year old'),
    ('eleven year-old'),
    ('eleven-year-old'),
    ('eleven years old'),
    ('elliot rodger'),
    ('elliot-rodger'),
    ('emitting faggot vibes'),
    ('eslpedonigger'),
    ('esoteric hitlerism'),
    ('esoteric neo-aryan hitlerist'),
    ('ethical rapist'),
    ('evilcunnygang'),
    ('extremist'),
    ('faaaaaggot'),
    ('fag'),
    ('fag beater'),
    ('fagdyke'),
    ('faggot'),
    ('faggot beater'),
    ('faggot hater'),
    ('faggot jackass'),
    ('faggotkitty'),
    ('faggotoid'),
    ('faggots'),
    ('faggots hater'),
    ('fag hater'),
    ('fagism'),
    ('fags hater'),
    ('fascist'),
    ('fat hate'),
    ('fatphobic'),
    ('fictohitler'),
    ('fifteen year old'),
    ('fifteen year-old'),
    ('fifteen-year-old'),
    ('fifteen years old'),
    ('fifteen yo'),
    ('filipina beater'),
    ('filipina hater'),
    ('filipinas hater'),
    ('filipino beater'),
    ('filipino hater'),
    ('filipino people beater'),
    ('filipino people hater'),
    ('filipinos hater'),
    ('five year old'),
    ('five year-old'),
    ('five-year-old'),
    ('five years old'),
    ('five yo'),
    ('flip beater'),
    ('flip hater'),
    ('flips hater'),
    ('former rapist'),
    ('fourteen year old'),
    ('fourteen year-old'),
    ('fourteen-year-old'),
    ('fourteen years old'),
    ('fourteen yo'),
    ('fratricide'),
    ('fuck asians'),
    ('fuck black people'),
    ('fuck blacks'),
    ('fuck brown people'),
    ('fuck buddhists'),
    ('fuck bug people'),
    ('fuck bugs'),
    ('fuck chinks'),
    ('fuck christianity'),
    ('fuck christians'),
    ('fuck coons'),
    ('fuck faggots'),
    ('fuck fags'),
    ('fuck filipinas'),
    ('fuck filipino people'),
    ('fuck filipinos'),
    ('fuck flips'),
    ('fuck gays'),
    ('fuck hinduim'),
    ('fuck hinduims'),
    ('fuck hindus'),
    ('fuck india'),
    ('fuck indians'),
    ('fucking faggot'),
    ('fuck irish "people"'),
    ('fuck irish people'),
    ('fuck islam'),
    ('fuck israel'),
    ('fuck jewish people'),
    ('fuck jews'),
    ('fuck judaism'),
    ('fuck kikes'),
    ('fuck latinos'),
    ('fuck lgbtq'),
    ('fuck loli'),
    ('fuck men'),
    ('fuck mexicans'),
    ('fuck minorities'),
    ('fuck mormons'),
    ('fuck muslims'),
    ('fuck my faggot life'),
    ('fuck my pathetic nigger life'),
    ('fuck nazis'),
    ('fuck niggers'),
    ('fuck nigs'),
    ('fuck norway'),
    ('fuck pakis'),
    ('fuck palestine'),
    ('fuck quebec'),
    ('fuck queers'),
    ('fuck terfs'),
    ('fuck the fags'),
    ('fuck trannies'),
    ('fuck ukraine'),
    ('fuck white people'),
    ('fuck whites'),
    ('fuck women'),
    ('fuck you kys'),
    ('fuck you nigger'),
    ('fuck zipperheads'),
    ('furry loli'),
    ('furry shota'),
    ('gang rape'),
    ('gangrape'),
    ('gas jew'),
    ('gas jews'),
    ('gay beater'),
    ('gay faggot'),
    ('gay hater'),
    ('gaynigger retard gang'),
    ('gays hater'),
    ('gay shota'),
    ('genocide'),
    ('getting raped'),
    ('gettingraped'),
    ('gf beater'),
    ('girlfaggot'),
    ('girlfailure abuser'),
    ('girl friend beater'),
    ('girlfriend beater'),
    ('globalist'),
    ('gook'),
    ('gooks'),
    ('gore'),
    ('gorecore'),
    ('gothic lolita'),
    ('grapist'),
    ('groomable'),
    ('#groomed'),
    ('groomed child'),
    ('groomer'),
    ('groom me'),
    ('groom me please'),
    ('guro lolita'),
    ('hail hitler'),
    ('hail victory'),
    ('hang myself'),
    ('hang yourself'),
    ('hasbulla'),
    ('hateasians'),
    ('hateblackpeople'),
    ('hateblacks'),
    ('hatebrownpeople'),
    ('hatebugpeople'),
    ('hatebugs'),
    ('hate chinks'),
    ('hatechinks'),
    ('hate faggots'),
    ('hatefaggots'),
    ('hate fags'),
    ('hatefags'),
    ('hatefilipinas'),
    ('hatefilipinopeople'),
    ('hatefilipinos'),
    ('hateflips'),
    ('hate gays'),
    ('hategays'),
    ('hateindians'),
    ('hateirish"people"'),
    ('hateirishpeople'),
    ('hate islam'),
    ('hateislam'),
    ('hate jews'),
    ('hatejews'),
    ('hate kikes'),
    ('hatekikes'),
    ('hatelatinos'),
    ('hate lgbt'),
    ('hatelgbt'),
    ('hate lgbtq'),
    ('hatelgbtq'),
    ('hate lgbtqia'),
    ('hatelgbtqia'),
    ('hate lgbtqqip2saa'),
    ('hatelgbtqqip2saa'),
    ('hate lgbttqqiaap'),
    ('hatelgbttqqiaap'),
    ('hate loli'),
    ('hateloli'),
    ('hate men'),
    ('hatemen'),
    ('hatemexicans'),
    ('hate minorities'),
    ('hateminorities'),
    ('hate muslims'),
    ('hatemuslims'),
    ('hatenazis'),
    ('hate niggers'),
    ('hateniggers'),
    ('hate nigs'),
    ('hatenigs'),
    ('hatepakis'),
    ('hatepoland'),
    ('hate queers'),
    ('hatequeers'),
    ('hate trannies'),
    ('hatetrannies'),
    ('hatewhitepeople'),
    ('hatewhites'),
    ('hate women'),
    ('hatewomen'),
    ('hatezipperheads'),
    ('heil hitler'),
    ('heil victory'),
    ('heterophobic'),
    ('hezbollah'),
    ('highschooler'),
    ('hilariously racist'),
    ('hindu hater'),
    ('hinduim hater'),
    ('hindus hater'),
    ('hitler'),
    ('hitlerchildrape1488'),
    ('hitlerchungus'),
    ('hitlercunnyrape1488'),
    ('hitler daughter'),
    ('hitler did nothing wrong'),
    ('hitler enjoyer'),
    ('hitler''s top guy'),
    ('hitler youth'),
    ('homicide'),
    ('homophobic'),
    ('homophobic and gay'),
    ('homophobic asf'),
    ('husband beater'),
    ('i abuse men'),
    ('i abuse women'),
    ('i am 10'),
    ('i am 10 years'),
    ('i am 10 years old'),
    ('i am 11 years old'),
    ('i am 12'),
    ('i am 12 years'),
    ('i am 12 years old'),
    ('i am 13'),
    ('i am 13 years'),
    ('i am 13 years old'),
    ('i am 14'),
    ('i am 14 years'),
    ('i am 14 years old'),
    ('i am 15'),
    ('i am 15 years'),
    ('i am 15 years old'),
    ('i am 16'),
    ('i am 16 years'),
    ('i am 16 years old'),
    ('i am 17'),
    ('i am 17 years'),
    ('i am 17 years old'),
    ('i am 5'),
    ('i am 5 years'),
    ('i am 5 years old'),
    ('i am 6'),
    ('i am 6 years'),
    ('i am 6 years old'),
    ('i am 7'),
    ('i am 7 years'),
    ('i am 7 years old'),
    ('i am 8'),
    ('i am 8 years'),
    ('i am 8 years old'),
    ('i am 9'),
    ('i am 9 years'),
    ('i am 9 years old'),
    ('i am a 10 year old'),
    ('i am a 10 year-old'),
    ('i am a 10 yo'),
    ('i am a 11 year old'),
    ('i am a 11 year-old'),
    ('i am a 12 year old'),
    ('i am a 12 year-old'),
    ('i am a 12 yo'),
    ('i am a 13 year old'),
    ('i am a 13 year-old'),
    ('i am a 13 yo'),
    ('i am a 14 year old'),
    ('i am a 14 year-old'),
    ('i am a 14 yo'),
    ('i am a 15 year old'),
    ('i am a 15 year-old'),
    ('i am a 15 yo'),
    ('i am a 16 year old'),
    ('i am a 16 year-old'),
    ('i am a 16 yo'),
    ('i am a 17 year old'),
    ('i am a 17 year-old'),
    ('i am a 17 yo'),
    ('i am a 5 year old'),
    ('i am a 5 year-old'),
    ('i am a 5 yo'),
    ('i am a 6 year old'),
    ('i am a 6 year-old'),
    ('i am a 6 yo'),
    ('i am a 7 year old'),
    ('i am a 7 year-old'),
    ('i am a 7 yo'),
    ('i am a 8 year old'),
    ('i am a 8 year-old'),
    ('i am a 8 yo'),
    ('i am a 9 year old'),
    ('i am a 9 year-old'),
    ('i am a 9 yo'),
    ('i am a eight year old'),
    ('i am a eight year-old'),
    ('i am a fifteen year old'),
    ('i am a fifteen year-old'),
    ('i am a fifteen yo'),
    ('i am a five year old'),
    ('i am a five year-old'),
    ('i am a five yo'),
    ('i am a fourteen year old'),
    ('i am a fourteen year-old'),
    ('i am a fourteen yo'),
    ('i am an 8 year old'),
    ('i am an 8 year-old'),
    ('i am an 8 yo'),
    ('i am an eight yo'),
    ('i am an eleven year old'),
    ('i am an eleven year-old'),
    ('i am a nine year old'),
    ('i am a nine year-old'),
    ('i am a nine yo'),
    ('i am a rapist'),
    ('i am a seventeen year old'),
    ('i am a seventeen year-old'),
    ('i am a seventeen yo'),
    ('i am a seven year old'),
    ('i am a seven year-old'),
    ('i am a seven yo'),
    ('i am a sex offender'),
    ('i am a sixteen year old'),
    ('i am a sixteen year-old'),
    ('i am a sixteen yo'),
    ('i am a six year old'),
    ('i am a six year-old'),
    ('i am a six yo'),
    ('i am a ten year old'),
    ('i am a ten year-old'),
    ('i am a ten yo'),
    ('i am a thirteen year old'),
    ('i am a thirteen year-old'),
    ('i am a thirteen yo'),
    ('i am a twelve year old'),
    ('i am a twelve year-old'),
    ('i am a twelve yo'),
    ('i am eight years old'),
    ('i am eleven years old'),
    ('i am fifteen years old'),
    ('i am five years old'),
    ('i am fourteen years old'),
    ('i am going bash your head in with a rock'),
    ('i am hanging myself'),
    ('i am nine years old'),
    ('i am not a rapist'),
    ('i am not a rapist anymore'),
    ('i am seventeen years old'),
    ('i am seven years old'),
    ('i am sixteen years old'),
    ('i am six years old'),
    ('i am ten years old'),
    ('i am thirteen years old'),
    ('i am twelve years old'),
    ('i beat women'),
    ('i blame the jews'),
    ('i cut myself'),
    ('i don''t like rape'),
    ('i dont like rape'),
    ('idon''tlikerape'),
    ('idontlikerape'),
    ('i enjoy rape'),
    ('ienjoyrape'),
    ('i enjoy raping'),
    ('i enjoy raping you'),
    ('i fucking hate asians'),
    ('i fucking hate black people'),
    ('i fucking hate blacks'),
    ('i fucking hate brown people'),
    ('i fucking hate bug people'),
    ('i fucking hate bugs'),
    ('i fucking hate chinks'),
    ('i fucking hate faggots'),
    ('i fucking hate fags'),
    ('i fucking hate filipinas'),
    ('i fucking hate filipino people'),
    ('i fucking hate filipinos'),
    ('i fucking hate flips'),
    ('i fucking hate gays'),
    ('i fucking hate indians'),
    ('i fucking hate irish "people"'),
    ('i fucking hate irish people'),
    ('i fucking hate islam'),
    ('i fucking hate jews'),
    ('i fucking hate kikes'),
    ('i fucking hate latinos'),
    ('i fucking hate loli'),
    ('i fucking hate men'),
    ('i fucking hate mexicans'),
    ('i fucking hate minorities'),
    ('i fucking hate muslims'),
    ('i fucking hate nazis'),
    ('i fucking hate niggers'),
    ('i fucking hate nigs'),
    ('i fucking hate pakis'),
    ('i fucking hate queers'),
    ('i fucking hate trannies'),
    ('i fucking hate white people'),
    ('i fucking hate whites'),
    ('i fucking hate women'),
    ('i fucking hate zipperheads'),
    ('i hate asians'),
    ('i hate black people'),
    ('i hate blacks'),
    ('i hate brown people'),
    ('i hate bug people'),
    ('i hate bugs'),
    ('i hate chinks'),
    ('i hate faggots'),
    ('i hate fags'),
    ('i hate filipinas'),
    ('i hate filipino people'),
    ('i hate filipinos'),
    ('i hate flips'),
    ('i hate gays'),
    ('i hate indians'),
    ('i hate irish "people"'),
    ('i hate irish people'),
    ('i hate islam'),
    ('i hate jews'),
    ('i hate kikes'),
    ('i hate latinos'),
    ('i hate lgbt'),
    ('i hate lgbtq'),
    ('i hate lgbtqia'),
    ('i hate lgbtqqip2saa'),
    ('i hate lgbttqqiaap'),
    ('i hate loli'),
    ('i hate men'),
    ('i hate mexicans'),
    ('i hate minorities'),
    ('i hate muslims'),
    ('i hate nazis'),
    ('i hate niggers'),
    ('i hate nigs'),
    ('i hate pakis'),
    ('i hate poland'),
    ('i hate queers'),
    ('i hate trannies'),
    ('i hate white people'),
    ('i hate whites'),
    ('i hate women'),
    ('i hate zipperheads'),
    ('i kill people'),
    ('i let my ex beat me for fun'),
    ('i''ll kill myself'),
    ('i love gore'),
    ('i love israel gon'),
    ('i love loli'),
    ('i love minors'),
    ('i love nazi'),
    ('i love nazis'),
    ('i love shota'),
    ('i love shotacon'),
    ('i''m 10'),
    ('i''m 12'),
    ('i''m 13'),
    ('i''m 14'),
    ('i''m 15'),
    ('i''m 16'),
    ('i''m 17'),
    ('i''m 5'),
    ('i''m 6'),
    ('i''m 7'),
    ('i''m 8'),
    ('i''m 9'),
    ('i''m a 10 year old'),
    ('i''m a 10 year-old'),
    ('i''m a 10 yo'),
    ('i''m a 11 year old'),
    ('i''m a 11 year-old'),
    ('i''m a 12 year old'),
    ('i''m a 12 year-old'),
    ('i''m a 12 yo'),
    ('i''m a 13 year old'),
    ('i''m a 13 year-old'),
    ('i''m a 13 yo'),
    ('i''m a 14 year old'),
    ('i''m a 14 year-old'),
    ('i''m a 14 yo'),
    ('i''m a 15 year old'),
    ('i''m a 15 year-old'),
    ('i''m a 15 yo'),
    ('i''m a 16 year old'),
    ('i''m a 16 year-old'),
    ('i''m a 16 yo'),
    ('i''m a 17 year old'),
    ('i''m a 17 year-old'),
    ('i''m a 17 yo'),
    ('i''m a 5 year old'),
    ('i''m a 5 year-old'),
    ('i''m a 5 yo'),
    ('i''m a 6 year old'),
    ('i''m a 6 year-old'),
    ('i''m a 6 yo'),
    ('i''m a 7 year old'),
    ('i''m a 7 year-old'),
    ('i''m a 7 yo'),
    ('i''m a 8 year old'),
    ('i''m a 8 year-old'),
    ('i''m a 8 yo'),
    ('i''m a 9 year old'),
    ('i''m a 9 year-old'),
    ('i''m a 9 yo'),
    ('i''m a eight year old'),
    ('i''m a eight year-old'),
    ('i''m a fifteen year old'),
    ('i''m a fifteen year-old'),
    ('i''m a fifteen yo'),
    ('i''m a five year old'),
    ('i''m a five year-old'),
    ('i''m a five yo'),
    ('i''m a fourteen year old'),
    ('i''m a fourteen year-old'),
    ('i''m a fourteen yo'),
    ('i''m against rape because kids are born'),
    ('i''magainstrapebecausekidsareborn'),
    ('i''m an eight yo'),
    ('i''m an eleven year old'),
    ('i''m an eleven year-old'),
    ('i''m a nine year old'),
    ('i''m a nine year-old'),
    ('i''m a nine yo'),
    ('i''m a rapist'),
    ('i''m a serial rapist'),
    ('i''m a seventeen year old'),
    ('i''m a seventeen year-old'),
    ('i''m a seventeen yo'),
    ('i''m a seven year old'),
    ('i''m a seven year-old'),
    ('i''m a seven yo'),
    ('i''m a sex offender'),
    ('i''m a sixteen year old'),
    ('i''m a sixteen year-old'),
    ('i''m a sixteen yo'),
    ('i''m a six year old'),
    ('i''m a six year-old'),
    ('i''m a six yo'),
    ('i''m a ten year old'),
    ('i''m a ten year-old'),
    ('i''m a ten yo'),
    ('i''m a thirteen year old'),
    ('i''m a thirteen year-old'),
    ('i''m a thirteen yo'),
    ('i''m a twelve year old'),
    ('i''m a twelve year-old'),
    ('i''m a twelve yo'),
    ('im gonna kms'),
    ('i''m not a rapist'),
    ('i''m not a rapist anymore'),
    ('i must rape'),
    ('imustrape'),
    ('incest'),
    ('india hater'),
    ('indian beater'),
    ('indian hater'),
    ('indians hater'),
    ('infanticide'),
    ('i rape twinks'),
    ('irapetwinks'),
    ('irish "people" beater'),
    ('irish people beater'),
    ('irish "people" hater'),
    ('irish people hater'),
    ('irl loli'),
    ('irl shota'),
    ('ironic rape'),
    ('ironicrape'),
    ('i should kms'),
    ('isil'),
    ('isis'),
    ('islam beater'),
    ('islam hater'),
    ('islamic state'),
    ('islamophobia'),
    ('islamophobic'),
    ('israel defence force'),
    ('israel defense force'),
    ('israel hater'),
    ('israeli defence force'),
    ('israeli defense force'),
    ('israeli revenue service'),
    ('its probably the jews'),
    ('i want to be groomed'),
    ('i will beat the shit out of you'),
    ('i will beat you with a rock'),
    ('i will hang myself'),
    ('i will hang myself while drunk'),
    ('i will kill myself'),
    ('i will kill myself in front of you'),
    ('i will kill myself on vc infront of you'),
    ('i will rape'),
    ('iwillrape'),
    ('i will rape women'),
    ('iwillrapewomen'),
    ('i will rape you'),
    ('iwillrapeyou'),
    ('i will sexually assault you'),
    ('jailbait'),
    ('jerusalem hate'),
    ('jew beater'),
    ('jew hate'),
    ('jew hater'),
    ('jewish hate foundation'),
    ('jewish people hater'),
    ('jew jitsu'),
    ('jews'),
    ('jews hater'),
    ('judaism hater'),
    ('just beat the shit out of me'),
    ('kekistan vs israel'),
    ('kiddie fiddler'),
    ('kike'),
    ('kike beater'),
    ('kike hater'),
    ('kikes'),
    ('kikes hater'),
    ('kikistan vs israel'),
    ('kill'),
    ('kill all anglos'),
    ('killallanglos'),
    ('kill all asians'),
    ('killallasians'),
    ('kill all black people'),
    ('killallblack people'),
    ('kill all blacks'),
    ('killallblacks'),
    ('kill all brown people'),
    ('killallbrown people'),
    ('kill all bug people'),
    ('killallbug people'),
    ('kill all bugs'),
    ('killallbugs'),
    ('kill all chinks'),
    ('killallchinks'),
    ('kill all faggots'),
    ('killallfaggots'),
    ('kill all fags'),
    ('killallfags'),
    ('kill all filipinas'),
    ('killallfilipinas'),
    ('kill all filipino people'),
    ('killallfilipino people'),
    ('kill all filipinos'),
    ('killallfilipinos'),
    ('kill all flips'),
    ('killallflips'),
    ('kill all gays'),
    ('killallgays'),
    ('kill all indians'),
    ('killallindians'),
    ('kill all irish "people"'),
    ('kill all irish people'),
    ('killallirish "people"'),
    ('killallirish people'),
    ('kill all islam'),
    ('killallislam'),
    ('kill all jews'),
    ('killalljews'),
    ('kill all kikes'),
    ('killallkikes'),
    ('kill all latinos'),
    ('killalllatinos'),
    ('kill all loli'),
    ('killallloli'),
    ('kill all men'),
    ('killallmen'),
    ('kill all mexicans'),
    ('killallmexicans'),
    ('kill all minorities'),
    ('killallminorities'),
    ('kill all muslims'),
    ('killallmuslims'),
    ('kill all nazis'),
    ('killallnazis'),
    ('kill all niggers'),
    ('killallniggers'),
    ('kill all nigs'),
    ('killallnigs'),
    ('kill all pakis'),
    ('killallpakis'),
    ('kill all queers'),
    ('killallqueers'),
    ('kill all trannies'),
    ('killalltrannies'),
    ('kill all white people'),
    ('killallwhite people'),
    ('kill all whites'),
    ('killallwhites'),
    ('kill all women'),
    ('killallwomen'),
    ('kill all zipperheads'),
    ('killallzipperheads'),
    ('kill arabs'),
    ('kill asians'),
    ('kill black people'),
    ('kill blacks'),
    ('kill brown people'),
    ('kill bug people'),
    ('kill bugs'),
    ('kill chinks'),
    ('killed'),
    ('killer'),
    ('kill everyone'),
    ('kill faggots'),
    ('kill fags'),
    ('kill fat people'),
    ('killfatpeople'),
    ('kill filipino people'),
    ('kill flips'),
    ('kill for me'),
    ('kill gays'),
    ('kill homeless people'),
    ('kill indians'),
    ('killing'),
    ('killing mself'),
    ('killing myself'),
    ('killing myself at 25'),
    ('killing myself at 40'),
    ('killing people'),
    ('killing people with rocks'),
    ('killing ppl w a rock'),
    ('kill irish "people"'),
    ('kill irish people'),
    ('kill islam'),
    ('kill jews'),
    ('kill kikes'),
    ('kill kill kill'),
    ('kill latinos'),
    ('kill lgbt'),
    ('kill lgbtq'),
    ('kill lgbtqia'),
    ('kill lgbtqqip2saa'),
    ('kill lgbttqqiaap'),
    ('kill loli'),
    ('kill men'),
    ('kill mexicans'),
    ('kill minorities'),
    ('kill muslims'),
    ('kill nazis'),
    ('kill nigg'),
    ('kill niggers'),
    ('kill niggers with rocks'),
    ('kill niggs'),
    ('kill nigs'),
    ('kill pakis'),
    ('kill people'),
    ('kill queers'),
    ('kills people'),
    ('kill the chinks'),
    ('kill the faggots'),
    ('kill the fags'),
    ('kill the gays'),
    ('kill the jews'),
    ('kill the kikes'),
    ('kill the men'),
    ('kill the minorities'),
    ('kill the muslims'),
    ('kill the niggers'),
    ('kill the nigs'),
    ('kill the queers'),
    ('kill the trannies'),
    ('kill the women'),
    ('kill trannies'),
    ('kill white people'),
    ('kill whites'),
    ('kill with hammer'),
    ('kill women'),
    ('kill yourself'),
    ('kill zipperheads'),
    ('kinda a fag'),
    ('kkk'),
    ('kms'),
    ('knife play'),
    ('knifeplay'),
    ('kool kids klub'),
    ('ku klux klan'),
    ('/kys/'),
    ('kys'),
    ('latino beater'),
    ('latino hater'),
    ('latinos hater'),
    ('let''s kill people'),
    ('lgbtq hater'),
    ('literally hitler'),
    ('lithuainan suicide enjoyer'),
    ('lithuania suicide enjoyer'),
    ('little rape slux'),
    ('littlerapeslux'),
    ('loli'),
    ('loli beater'),
    ('lolicon'),
    ('lolicon lerix'),
    ('lolicon''s fucking disgusting'),
    ('lolicon''s fucking gross'),
    ('lolicore'),
    ('loli furry'),
    ('loli hater'),
    ('loli in early 20s'),
    ('loli rape'),
    ('lolirape'),
    ('lolisho'),
    ('lolita'),
    ('lolita fashion'),
    ('man hater'),
    ('map'),
    ('mass shooter'),
    ('mass shooter fan club'),
    ('matricide'),
    ('max prestige faggot'),
    ('men beater'),
    ('men hater'),
    ('mexican beater'),
    ('mexican hater'),
    ('mexicans hater'),
    ('might be a pedo'),
    ('might be racist'),
    ('mildly racist'),
    ('minor'),
    ('minor attracted person'),
    ('minor-attracted person'),
    ('minor attracted persons'),
    ('minor-attracted persons'),
    ('minorities hater'),
    ('minority beater'),
    ('minority hater'),
    ('minor minor'),
    ('minorminor'),
    ('minor minor minor'),
    ('minorminorminor'),
    ('minor minor minor minor'),
    ('minorminorminorminor'),
    ('minor minor minor minor minor'),
    ('minorminorminorminorminor'),
    ('minor minor minor minor minor minor'),
    ('minorminorminorminorminorminor'),
    ('minor minor minor minor minor minor minor'),
    ('minorminorminorminorminorminorminor'),
    ('minors'),
    ('misandrist'),
    ('misandry'),
    ('misogynist'),
    ('misogynistic'),
    ('misogyny'),
    ('mnsfw'),
    ('mnwo'),
    ('moralfags kys'),
    ('mormon hater'),
    ('mormons hater'),
    ('most racist kanye fan'),
    ('most racist man alive'),
    ('mr suicide sheep'),
    ('mrsuicidesheep'),
    ('mudslime'),
    ('mudslimes'),
    ('murder murder kill kill'),
    ('murder trannies'),
    ('muslim beater'),
    ('muslim hater'),
    ('muslims hater'),
    ('nate higgers'),
    ('national socialism'),
    ('national socialist'),
    ('nato tranny'),
    ('natsoc'),
    ('nazi'),
    ('nazi beater'),
    ('nazi hater'),
    ('nazi leader'),
    ('nazis hater'),
    ('necrophile'),
    ('neega'),
    ('neeger'),
    ('negroid'),
    ('neo nazi'),
    ('neo-nazi'),
    ('nig'),
    ('nig beater'),
    ('nigg'),
    ('nigga'),
    ('niggah'),
    ('nigga hater'),
    ('niggarapist'),
    ('nigger'),
    ('nigger beater'),
    ('nigger faggot'),
    ('niggerfaggot'),
    ('nigger hater'),
    ('niggerlicious'),
    ('nigger rapist'),
    ('niggers'),
    ('niggers hater'),
    ('niggger'),
    ('niggot'),
    ('niggress'),
    ('niggy'),
    ('nig hater'),
    ('nigs'),
    ('nigs hater'),
    ('nine year old'),
    ('nine year-old'),
    ('nine-year-old'),
    ('nine years old'),
    ('nine yo'),
    ('nonconsensual hand holding'),
    ('norway hater'),
    ('not 18'),
    ('not a fan of trans personally'),
    ('not a paedophile'),
    ('not a pedophile'),
    ('not over 18'),
    ('not suicidal'),
    ('not trans'),
    ('nsbm'),
    ('nuke africa'),
    ('nuke china'),
    ('nuke israel'),
    ('onlyfans'),
    ('op is a faggot'),
    ('osama bin laden'),
    ('paedo'),
    ('paedokiller'),
    ('paedophile'),
    ('paedophiles'),
    ('pajeet'),
    ('pajeets'),
    ('paki'),
    ('paki beater'),
    ('paki hater'),
    ('pakis hater'),
    ('pakkis'),
    ('palestine hater'),
    ('paraphile'),
    ('patricide'),
    ('pattern noticer'),
    ('pdf file'),
    ('pedbait'),
    ('pedo'),
    ('pedokiller'),
    ('pedomom'),
    ('pedophile'),
    ('pedophiles'),
    ('pedophilia'),
    ('pedos kys'),
    ('pedoslut'),
    ('pervert degenerate faggot'),
    ('petplay'),
    ('piss'),
    ('pissfaggot'),
    ('please groom me'),
    ('please hang yourself'),
    ('please kill yourself'),
    ('please rape me'),
    ('pleaserapeme'),
    ('please rape my face'),
    ('pleaserapemyface'),
    ('pls hit me and abuse me'),
    ('/pol/ niggas'),
    ('potential mass shooter'),
    ('ppl saying nigga instead of nigger cucks'),
    ('ppls saying nigga instead of nigger suck'),
    ('prevert degenerate faggot'),
    ('pro faggotry'),
    ('professional groomer'),
    ('prostitute'),
    ('q'),
    ('quebec hater'),
    ('queer beater'),
    ('queer hater'),
    ('queers hater'),
    ('race war now'),
    ('racism'),
    ('racism inc'),
    ('racism is funny'),
    ('/racist'),
    ('/racist/'),
    ('racist'),
    ('racist as a joke'),
    ('racist minority'),
    ('/racists'),
    ('/racists/'),
    ('racists kys'),
    ('radfemhitler fan club'),
    ('rag head'),
    ('raghead'),
    ('rag heads'),
    ('ragheads'),
    ('rape'),
    ('rapebastard club'),
    ('rapebastardclub'),
    ('rape bunny'),
    ('rapebunny'),
    ('rapebutnotinanindianway'),
    ('raped'),
    ('rapefag'),
    ('rape in india'),
    ('rapeinindia'),
    ('rape in india today'),
    ('rapeinindiatoday'),
    ('rape isn''t real'),
    ('rapeisn''treal'),
    ('rape israel'),
    ('rapeisrael'),
    ('rapeman'),
    ('rapemaxxing'),
    ('rape me'),
    ('rapeme'),
    ('rapemeat'),
    ('rape men'),
    ('rapemen'),
    ('rape music'),
    ('rapemusic'),
    ('rape my face'),
    ('rapemyface'),
    ('rape people'),
    ('rapepeople'),
    ('rape play'),
    ('rapeplay'),
    ('raper'),
    ('rapes'),
    ('rapes people'),
    ('rapespeople'),
    ('rape survivor'),
    ('rapesurvivor'),
    ('rape suvivor'),
    ('rapesuvivor'),
    ('rapetoy'),
    ('rape victim'),
    ('rapevictim'),
    ('rape women'),
    ('rapewomen'),
    ('raping'),
    ('rapist'),
    ('rapist homo thug'),
    ('rapists'),
    ('respect niggers'),
    ('retard'),
    ('retarded faggot'),
    ('retarded nigger'),
    ('roastie'),
    ('roasty'),
    ('romantic woman beater'),
    ('ropemaxxing'),
    ('russophobic'),
    ('sandnigger'),
    ('say you love me or i will kill myself'),
    ('school shooter'),
    ('secretly not racist'),
    ('self harm'),
    ('self-harm'),
    ('selfharm'),
    ('seller'),
    ('selling'),
    ('selling drugs'),
    ('seppo'),
    ('seppos'),
    ('serial killer'),
    ('seventeen year old'),
    ('seventeen year-old'),
    ('seventeen-year-old'),
    ('seventeen years old'),
    ('seventeen yo'),
    ('seven year old'),
    ('seven year-old'),
    ('seven-year-old'),
    ('seven years old'),
    ('seven yo'),
    ('sex offender'),
    ('sexual assault'),
    ('sexual assault victim'),
    ('sexually assaults you'),
    ('sex worker'),
    ('sexworker'),
    ('shota'),
    ('shotabait'),
    ('shotacon'),
    ('shota lover'),
    ('shota raper'),
    ('shotaraper'),
    ('should die'),
    ('should kill self'),
    ('shtwt'),
    ('sieg heil'),
    ('sixteen year old'),
    ('sixteen year-old'),
    ('sixteen-year-old'),
    ('sixteen years old'),
    ('sixteen yo'),
    ('six year old'),
    ('six year-old'),
    ('six-year-old'),
    ('six years old'),
    ('six yo'),
    ('skinny nigger'),
    ('slave owner club'),
    ('slightly racist'),
    ('snuff'),
    ('sometimes i feel misandrist'),
    ('sororicide'),
    ('/soy/'),
    ('soy'),
    ('soyjackparty'),
    ('soyjak'),
    ('soyjak party'),
    ('soy maxing'),
    ('soyposter'),
    ('soyteen'),
    ('spic'),
    ('spouse beater'),
    ('straight shota'),
    ('stupid faggot little cocksucker'),
    ('suicidal'),
    ('suicidal tendencies'),
    ('suicide'),
    ('suicide bomber'),
    ('suicide boy'),
    ('suicide boys'),
    ('suicide by boeing'),
    ('suicide idealizer'),
    ('suicidein1month'),
    ('suicidein2months'),
    ('suicide in 3 months'),
    ('suicidein3months'),
    ('suicidein4months'),
    ('suicidein5months'),
    ('suicidein6months'),
    ('suicide might be the right option for you'),
    ('suicide room'),
    ('suicide watch'),
    ('supreme gentleman'),
    ('supreme-gentleman'),
    ('talmud denouncer'),
    ('teen suicide'),
    ('ten year old'),
    ('ten year-old'),
    ('ten-year-old'),
    ('ten years old'),
    ('ten yo'),
    ('terf'),
    ('the fag hater'),
    ('the fags hater'),
    ('the negroid contingency'),
    ('thirteen year old'),
    ('thirteen year-old'),
    ('thirteen-year-old'),
    ('thirteen years old'),
    ('thirteen yo'),
    ('this faggot can throw hands'),
    ('threat to national security'),
    ('thug rape'),
    ('thugrape'),
    ('tkd'),
    ('tnd'),
    ('total kike victory'),
    ('total nigger life'),
    ('touch me without consent'),
    ('towel head'),
    ('towelhead'),
    ('towel heads'),
    ('towelheads'),
    ('trannie beater'),
    ('trannies'),
    ('trannies are made up'),
    ('trannies hater'),
    ('tranny'),
    ('tranny hater'),
    ('trannyism'),
    ('trans exclusion'),
    ('trans-exclusion'),
    ('trans exclusionary'),
    ('trans-exclusionary'),
    ('transphobe'),
    ('transphobia'),
    ('transphobic'),
    ('troon'),
    ('troonphobic'),
    ('twelve year old'),
    ('twelve year-old'),
    ('twelve-year-old'),
    ('twelve years old'),
    ('twelve yo'),
    ('twink beater'),
    ('twinkbeater'),
    ('twitter niggers kys'),
    ('under 18'),
    ('under age'),
    ('underage'),
    ('under aged'),
    ('underaged'),
    ('under eighteen'),
    ('uoh'),
    ('uohhh'),
    ('uoooooooooooooooooooooooooooooooooooooooh'),
    ('verbal abuse'),
    ('violencepilled'),
    ('virgin suicide'),
    ('wannabe victim'),
    ('wants to be groomed'),
    ('white beater'),
    ('white is right'),
    ('white people beater'),
    ('white people hater'),
    ('white person hater'),
    ('white power'),
    ('white pride'),
    ('whites hater'),
    ('white supremacy'),
    ('wife beater'),
    ('will hang myself while drunk'),
    ('will kill myself'),
    ('will kill myself on vc infront of you'),
    ('wog'),
    ('wogs'),
    ('woman beater'),
    ('woman hater'),
    ('women beater'),
    ('women hater'),
    ('would kill'),
    ('xenophobia'),
    ('xenophobic'),
    ('you hate me because i was raped'),
    ('youhatemebecauseiwasraped'),
    ('you should hang myself'),
    ('you should hang yourself'),
    ('you should kill yourself'),
    ('you should kill yourself now'),
    ('ywnbaw'),
    ('zionist'),
    ('zipperhead'),
    ('zipperhead beater'),
    ('zipperheads'),
    ('zoophile')
ON CONFLICT (name) DO NOTHING;

DELETE FROM
    club
USING
    banned_club
WHERE
    LOWER(club.name) = banned_club.name;
