INSERT INTO banned_club (name)
VALUES
    ('10'),
    ('10y'),
    ('10 year old'),
    ('10 year-old'),
    ('10-year-old'),
    ('10 years'),
    ('10years'),
    ('10 years old'),
    ('10 yo'),
    ('10yo'),
    ('12'),
    ('12y'),
    ('12 year old'),
    ('12 year-old'),
    ('12-year-old'),
    ('12 years'),
    ('12years'),
    ('12 years old'),
    ('12 yo'),
    ('12yo'),
    ('13'),
    ('13y'),
    ('13 year old'),
    ('13 year-old'),
    ('13-year-old'),
    ('13 years'),
    ('13years'),
    ('13 years old'),
    ('13 yo'),
    ('13yo'),
    ('14'),
    ('1488'),
    ('14y'),
    ('14 year old'),
    ('14 year-old'),
    ('14-year-old'),
    ('14 years'),
    ('14years'),
    ('14 years old'),
    ('14 yo'),
    ('14yo'),
    ('15'),
    ('15y'),
    ('15 year old'),
    ('15 year-old'),
    ('15-year-old'),
    ('15 years'),
    ('15years'),
    ('15 years old'),
    ('15 yo'),
    ('15yo'),
    ('16'),
    ('16y'),
    ('16 year old'),
    ('16 year-old'),
    ('16-year-old'),
    ('16 years'),
    ('16years'),
    ('16 years old'),
    ('16 yo'),
    ('16yo'),
    ('17'),
    ('17y'),
    ('17 year old'),
    ('17 year-old'),
    ('17-year-old'),
    ('17 years'),
    ('17years'),
    ('17 years old'),
    ('17 yo'),
    ('17yo'),
    ('18'),
    ('311'),
    ('38'),
    ('4chan is for faggots'),
    ('5'),
    ('50 suicide attempts'),
    ('5y'),
    ('5 year old'),
    ('5 year-old'),
    ('5-year-old'),
    ('5 years'),
    ('5years'),
    ('5 years old'),
    ('5 yo'),
    ('5yo'),
    ('6'),
    ('6y'),
    ('6 year old'),
    ('6 year-old'),
    ('6-year-old'),
    ('6 years'),
    ('6years'),
    ('6 years old'),
    ('6 yo'),
    ('6yo'),
    ('7'),
    ('7y'),
    ('7 year old'),
    ('7 year-old'),
    ('7-year-old'),
    ('7 years'),
    ('7years'),
    ('7 years old'),
    ('7 yo'),
    ('7yo'),
    ('8'),
    ('88'),
    ('8y'),
    ('8 year old'),
    ('8 year-old'),
    ('8-year-old'),
    ('8 years'),
    ('8years'),
    ('8 years old'),
    ('8 yo'),
    ('8yo'),
    ('9'),
    ('9y'),
    ('9 year old'),
    ('9 year-old'),
    ('9-year-old'),
    ('9 years'),
    ('9years'),
    ('9 years old'),
    ('9 yo'),
    ('9yo'),
    ('a10 aryan'),
    ('adolf hitler'),
    ('age gap'),
    ('age play'),
    ('agere'),
    ('age regress'),
    ('age regressor'),
    ('allah is a jew'),
    ('anti-faggotry'),
    ('anti-lgbtq'),
    ('anti-lgbtqiap'),
    ('aryan'),
    ('aryan emperor'),
    ('aryan jihad'),
    ('aryans'),
    ('aryanx'),
    ('assisted suicide'),
    ('beaner'),
    ('beating up minorities'),
    ('bestiality'),
    ('boykisser'),
    ('boy rapist'),
    ('brown racist'),
    ('bug killer'),
    ('buying drugs'),
    ('certified minor'),
    ('child abuse'),
    ('child porn'),
    ('child rape'),
    ('child rapist'),
    ('child trafficker'),
    ('child traficker'),
    ('chink'),
    ('chink hater'),
    ('chinks'),
    ('coal burner'),
    ('coalburner'),
    ('coal burners'),
    ('coalburners'),
    ('coon'),
    ('coons'),
    ('cotton picker'),
    ('cunny'),
    ('cunny archive'),
    ('cunnyborea'),
    ('cunny cumdump'),
    ('cunny rape'),
    ('cunnyseur'),
    ('cutter'),
    ('death to america'),
    ('death to israel'),
    ('domestic abuse'),
    ('don''t be trans'),
    ('dothead'),
    ('drug dealer'),
    ('elliot rodger'),
    ('elliot-rodger'),
    ('emitting faggot vibes'),
    ('eslpedonigger'),
    ('esoteric hitlerism'),
    ('esoteric neo-aryan hitlerist'),
    ('ethical rapist'),
    ('evilcunnygang'),
    ('faggot'),
    ('faggot hater'),
    ('faggot jackass'),
    ('faggotoid'),
    ('faggots'),
    ('fag hater'),
    ('fagism'),
    ('fatphobic'),
    ('fictohitler'),
    ('former rapist'),
    ('fucking faggot'),
    ('fuck islam'),
    ('fuck jews'),
    ('fuck lgbtq'),
    ('fuck my faggot life'),
    ('fuck my pathetic nigger life'),
    ('fuck you kys'),
    ('fuck you nigger'),
    ('furry loli'),
    ('furry shota'),
    ('gas jew'),
    ('gas jews'),
    ('gay faggot'),
    ('gay hater'),
    ('gaynigger retard gang'),
    ('gay shota'),
    ('girlfaggot'),
    ('globalist'),
    ('gook'),
    ('gooks'),
    ('gore'),
    ('gothic lolita'),
    ('grapist'),
    ('groomable'),
    ('groomed child'),
    ('groomer'),
    ('groom me please'),
    ('guro lolita'),
    ('hail hitler'),
    ('hail victory'),
    ('hate chinks'),
    ('hate faggots'),
    ('hate fags'),
    ('hate gays'),
    ('hate islam'),
    ('hate jews'),
    ('hate kikes'),
    ('hate loli'),
    ('hate men'),
    ('hate minorities'),
    ('hate muslims'),
    ('hate niggers'),
    ('hate nigs'),
    ('hate queers'),
    ('hate trannies'),
    ('hate women'),
    ('heil hitler'),
    ('heil victory'),
    ('highschooler'),
    ('hilariously racist'),
    ('hitler'),
    ('hitlerchildrape1488'),
    ('hitlerchungus'),
    ('hitlercunnyrape1488'),
    ('hitler daughter'),
    ('hitler did nothing wrong'),
    ('hitler enjoyer'),
    ('hitler''s top guy'),
    ('hitler youth'),
    ('homophobic'),
    ('i am 10'),
    ('i am 10 years'),
    ('i am 10 years old'),
    ('i am 12'),
    ('i am 12 years'),
    ('i am 12 years old'),
    ('i am 13'),
    ('i am 13 years'),
    ('i am 13 years old'),
    ('i am 14'),
    ('i am 14 years'),
    ('i am 14 years old'),
    ('i am 15'),
    ('i am 15 years'),
    ('i am 15 years old'),
    ('i am 16'),
    ('i am 16 years'),
    ('i am 16 years old'),
    ('i am 17'),
    ('i am 17 years'),
    ('i am 17 years old'),
    ('i am 5'),
    ('i am 5 years'),
    ('i am 5 years old'),
    ('i am 6'),
    ('i am 6 years'),
    ('i am 6 years old'),
    ('i am 7'),
    ('i am 7 years'),
    ('i am 7 years old'),
    ('i am 8'),
    ('i am 8 years'),
    ('i am 8 years old'),
    ('i am 9'),
    ('i am 9 years'),
    ('i am 9 years old'),
    ('i am a 10 year old'),
    ('i am a 10 year-old'),
    ('i am a 10 yo'),
    ('i am a 12 year old'),
    ('i am a 12 year-old'),
    ('i am a 12 yo'),
    ('i am a 13 year old'),
    ('i am a 13 year-old'),
    ('i am a 13 yo'),
    ('i am a 14 year old'),
    ('i am a 14 year-old'),
    ('i am a 14 yo'),
    ('i am a 15 year old'),
    ('i am a 15 year-old'),
    ('i am a 15 yo'),
    ('i am a 16 year old'),
    ('i am a 16 year-old'),
    ('i am a 16 yo'),
    ('i am a 17 year old'),
    ('i am a 17 year-old'),
    ('i am a 17 yo'),
    ('i am a 5 year old'),
    ('i am a 5 year-old'),
    ('i am a 5 yo'),
    ('i am a 6 year old'),
    ('i am a 6 year-old'),
    ('i am a 6 yo'),
    ('i am a 7 year old'),
    ('i am a 7 year-old'),
    ('i am a 7 yo'),
    ('i am a 8 year old'),
    ('i am a 8 year-old'),
    ('i am a 8 yo'),
    ('i am a 9 year old'),
    ('i am a 9 year-old'),
    ('i am a 9 yo'),
    ('i don''t like rape'),
    ('i dont like rape'),
    ('i fucking hate chinks'),
    ('i fucking hate faggots'),
    ('i fucking hate fags'),
    ('i fucking hate gays'),
    ('i fucking hate islam'),
    ('i fucking hate jews'),
    ('i fucking hate kikes'),
    ('i fucking hate loli'),
    ('i fucking hate men'),
    ('i fucking hate minorities'),
    ('i fucking hate muslims'),
    ('i fucking hate niggers'),
    ('i fucking hate nigs'),
    ('i fucking hate queers'),
    ('i fucking hate trannies'),
    ('i fucking hate women'),
    ('i hate chinks'),
    ('i hate faggots'),
    ('i hate fags'),
    ('i hate gays'),
    ('i hate islam'),
    ('i hate jews'),
    ('i hate kikes'),
    ('i hate loli'),
    ('i hate men'),
    ('i hate minorities'),
    ('i hate muslims'),
    ('i hate niggers'),
    ('i hate nigs'),
    ('i hate queers'),
    ('i hate trannies'),
    ('i hate women'),
    ('i kill people'),
    ('i love israel gon'),
    ('i love loli'),
    ('i love minors'),
    ('i love nazi'),
    ('i love nazis'),
    ('i love shota'),
    ('i love shotacon'),
    ('i''m 10'),
    ('i''m 12'),
    ('i''m 13'),
    ('i''m 14'),
    ('i''m 15'),
    ('i''m 16'),
    ('i''m 17'),
    ('i''m 5'),
    ('i''m 6'),
    ('i''m 7'),
    ('i''m 8'),
    ('i''m 9'),
    ('i''m a 10 year old'),
    ('i''m a 10 year-old'),
    ('i''m a 10 yo'),
    ('i''m a 12 year old'),
    ('i''m a 12 year-old'),
    ('i''m a 12 yo'),
    ('i''m a 13 year old'),
    ('i''m a 13 year-old'),
    ('i''m a 13 yo'),
    ('i''m a 14 year old'),
    ('i''m a 14 year-old'),
    ('i''m a 14 yo'),
    ('i''m a 15 year old'),
    ('i''m a 15 year-old'),
    ('i''m a 15 yo'),
    ('i''m a 16 year old'),
    ('i''m a 16 year-old'),
    ('i''m a 16 yo'),
    ('i''m a 17 year old'),
    ('i''m a 17 year-old'),
    ('i''m a 17 yo'),
    ('i''m a 5 year old'),
    ('i''m a 5 year-old'),
    ('i''m a 5 yo'),
    ('i''m a 6 year old'),
    ('i''m a 6 year-old'),
    ('i''m a 6 yo'),
    ('i''m a 7 year old'),
    ('i''m a 7 year-old'),
    ('i''m a 7 yo'),
    ('i''m a 8 year old'),
    ('i''m a 8 year-old'),
    ('i''m a 8 yo'),
    ('i''m a 9 year old'),
    ('i''m a 9 year-old'),
    ('i''m a 9 yo'),
    ('i''m a serial rapist'),
    ('im gonna kms'),
    ('incest'),
    ('i rape twinks'),
    ('irl loli'),
    ('irl shota'),
    ('ironic rape'),
    ('ironicrape'),
    ('i should kms'),
    ('islam hater'),
    ('islamophobic'),
    ('israel defense force'),
    ('israeli defence force'),
    ('israeli defense force'),
    ('israeli revenue service'),
    ('its probably the jews'),
    ('i want to be groomed'),
    ('i will kill myself in front of you'),
    ('jailbait'),
    ('jerusalem hate'),
    ('jew hate'),
    ('jew hater'),
    ('jewish hate foundation'),
    ('jew jitsu'),
    ('jews'),
    ('kekistan vs israel'),
    ('kike'),
    ('kike hater'),
    ('kikes'),
    ('kikistan vs israel'),
    ('kill'),
    ('kill all chinks'),
    ('kill all faggots'),
    ('kill all fags'),
    ('kill all gays'),
    ('kill all islam'),
    ('kill all jews'),
    ('kill all kikes'),
    ('kill all loli'),
    ('kill all men'),
    ('kill all minorities'),
    ('kill all muslims'),
    ('kill all niggers'),
    ('kill all nigs'),
    ('kill all queers'),
    ('kill all trannies'),
    ('kill all women'),
    ('kill arabs'),
    ('killed'),
    ('killer'),
    ('kill everyone'),
    ('kill for me'),
    ('kill gays'),
    ('kill homeless people'),
    ('killing'),
    ('killing myself at 25'),
    ('killing myself at 40'),
    ('killing people'),
    ('killing people with rocks'),
    ('killing ppl w a rock'),
    ('kill jews'),
    ('kill kill kill'),
    ('kill men'),
    ('kill nazis'),
    ('kill nigg'),
    ('kill niggers'),
    ('kill niggers with rocks'),
    ('kill niggs'),
    ('kill nigs'),
    ('kill people'),
    ('kills people'),
    ('kill the chinks'),
    ('kill the faggots'),
    ('kill the fags'),
    ('kill the gays'),
    ('kill the jews'),
    ('kill the kikes'),
    ('kill the men'),
    ('kill the minorities'),
    ('kill the muslims'),
    ('kill the niggers'),
    ('kill the nigs'),
    ('kill the queers'),
    ('kill the trannies'),
    ('kill the women'),
    ('kill with hammer'),
    ('kill women'),
    ('kill yourself'),
    ('kkk'),
    ('kms'),
    ('knife play'),
    ('knifeplay'),
    ('kool kids klub'),
    ('ku klux klan'),
    ('kys'),
    ('lgbtq hater'),
    ('literally hitler'),
    ('lithuainan suicide enjoyer'),
    ('lithuania suicide enjoyer'),
    ('loli'),
    ('lolicon'),
    ('lolicon lerix'),
    ('lolicon''s fucking disgusting'),
    ('lolicon''s fucking gross'),
    ('lolicore'),
    ('loli furry'),
    ('loli in early 20s'),
    ('loli rape'),
    ('lolisho'),
    ('lolita'),
    ('lolita fashion'),
    ('man hater'),
    ('map'),
    ('max prestige faggot'),
    ('might be a pedo'),
    ('might be racist'),
    ('mildly racist'),
    ('minor'),
    ('minority hater'),
    ('minor minor'),
    ('minorminor'),
    ('minor minor minor'),
    ('minorminorminor'),
    ('minor minor minor minor'),
    ('minorminorminorminor'),
    ('minor minor minor minor minor'),
    ('minorminorminorminorminor'),
    ('minor minor minor minor minor minor'),
    ('minorminorminorminorminorminor'),
    ('minor minor minor minor minor minor minor'),
    ('minorminorminorminorminorminorminor'),
    ('minors'),
    ('misogynist'),
    ('most racist man alive'),
    ('mudslime'),
    ('mudslimes'),
    ('murder murder kill kill'),
    ('murder trannies'),
    ('muslim hater'),
    ('nate higgers'),
    ('national socialism'),
    ('nato tranny'),
    ('nazi'),
    ('nazi leader'),
    ('necrophile'),
    ('neega'),
    ('neeger'),
    ('neo nazi'),
    ('neo-nazi'),
    ('nig'),
    ('nigga'),
    ('niggah'),
    ('nigga hater'),
    ('niggarapist'),
    ('nigger'),
    ('nigger faggot'),
    ('niggerfaggot'),
    ('nigger hater'),
    ('niggerlicious'),
    ('nigger rapist'),
    ('niggger'),
    ('niggot'),
    ('niggress'),
    ('niggy'),
    ('nig hater'),
    ('nigs'),
    ('not 18'),
    ('not a fan of trans personally'),
    ('not suicidal'),
    ('not trans'),
    ('nuke africa'),
    ('nuke china'),
    ('nuke israel'),
    ('onlyfans'),
    ('op is a faggot'),
    ('paedo'),
    ('paedophile'),
    ('paedophiles'),
    ('pajeet'),
    ('pajeets'),
    ('paki'),
    ('pakkis'),
    ('paraphile'),
    ('pattern noticer'),
    ('pdf file'),
    ('pedbait'),
    ('pedo'),
    ('pedomom'),
    ('pedophile'),
    ('pedophiles'),
    ('pedophilia'),
    ('pervert degenerate faggot'),
    ('petplay'),
    ('piss'),
    ('pissfaggot'),
    ('ppl saying nigga instead of nigger cucks'),
    ('ppls saying nigga instead of nigger suck'),
    ('prevert degenerate faggot'),
    ('pro faggotry'),
    ('prostitute'),
    ('q'),
    ('queer hater'),
    ('race war now'),
    ('racism'),
    ('racism inc'),
    ('racism is funny'),
    ('/racist'),
    ('racist'),
    ('racist as a joke'),
    ('racist minority'),
    ('racists kys'),
    ('radfemhitler fan club'),
    ('rag head'),
    ('raghead'),
    ('rag heads'),
    ('ragheads'),
    ('rape'),
    ('rape bunny'),
    ('raped'),
    ('rapefag'),
    ('rape israel'),
    ('rapeman'),
    ('rapemaxxing'),
    ('rape me'),
    ('rapemeat'),
    ('rape play'),
    ('raper'),
    ('raping'),
    ('rapist'),
    ('rapist homo thug'),
    ('rapists'),
    ('respect niggers'),
    ('retard'),
    ('retarded faggot'),
    ('retarded nigger'),
    ('roastie'),
    ('roasty'),
    ('sandnigger'),
    ('self harm'),
    ('self-harm'),
    ('seller'),
    ('selling'),
    ('selling drugs'),
    ('seppo'),
    ('seppos'),
    ('serial killer'),
    ('shota'),
    ('shotabait'),
    ('shotacon'),
    ('shota lover'),
    ('shota raper'),
    ('should kill self'),
    ('sieg heil'),
    ('skinny nigger'),
    ('slave owner club'),
    ('slightly racist'),
    ('snuff'),
    ('/soy/'),
    ('soyjak party'),
    ('spic'),
    ('straight shota'),
    ('stupid faggot little cocksucker'),
    ('suicidal'),
    ('suicide'),
    ('suicide bomber'),
    ('suicide by boeing'),
    ('suicide idealizer'),
    ('suicide in 3 months'),
    ('suicide might be the right option for you'),
    ('suicide watch'),
    ('supreme gentleman'),
    ('supreme-gentleman'),
    ('talmud denouncer'),
    ('teen suicide'),
    ('terf'),
    ('this faggot can throw hands'),
    ('thug rape'),
    ('tkd'),
    ('tnd'),
    ('total kike victory'),
    ('total nigger life'),
    ('towel head'),
    ('towelhead'),
    ('towel heads'),
    ('towelheads'),
    ('trannies'),
    ('trannies are made up'),
    ('tranny'),
    ('tranny hater'),
    ('trannyism'),
    ('transphobe'),
    ('transphobic'),
    ('twitter niggers kys'),
    ('under 18'),
    ('under age'),
    ('underage'),
    ('under aged'),
    ('underaged'),
    ('under eighteen'),
    ('white power'),
    ('white pride'),
    ('white supremacy'),
    ('will kill myself'),
    ('woman hater'),
    ('you should kill yourself now'),
    ('ywnbaw'),
    ('zionist'),
    ('zipperhead'),
    ('zipperheads'),
    ('zoophile')
ON CONFLICT (name) DO NOTHING;

DELETE FROM
    club
USING
    banned_club
WHERE
    LOWER(club.name) = banned_club.name;
