INSERT INTO banned_club (name)
VALUES
    ('/kys/'),
    ('/pol/ niggas'),
    ('/racist'),
    ('/soy/'),
    ('10 year old'),
    ('10 year-old'),
    ('10 years old'),
    ('10 years'),
    ('10 yo'),
    ('10'),
    ('10-year-old'),
    ('10y'),
    ('10years'),
    ('10yo'),
    ('11 year old'),
    ('11 year-old'),
    ('11 years old'),
    ('11-year-old'),
    ('12 year old'),
    ('12 year-old'),
    ('12 years old'),
    ('12 years'),
    ('12 yo'),
    ('12'),
    ('12-year-old'),
    ('12y'),
    ('12years'),
    ('12yo'),
    ('13 year old'),
    ('13 year-old'),
    ('13 years old'),
    ('13 years'),
    ('13 yo'),
    ('13'),
    ('13-year-old'),
    ('13y'),
    ('13years'),
    ('13yo'),
    ('14 year old'),
    ('14 year-old'),
    ('14 years old'),
    ('14 years'),
    ('14 yo'),
    ('14'),
    ('14-year-old'),
    ('1488'),
    ('14y'),
    ('14years'),
    ('14yo'),
    ('15 year old'),
    ('15 year-old'),
    ('15 years old'),
    ('15 years'),
    ('15 yo'),
    ('15'),
    ('15-year-old'),
    ('15y'),
    ('15years'),
    ('15yo'),
    ('16 year old'),
    ('16 year-old'),
    ('16 years old'),
    ('16 years'),
    ('16 yo'),
    ('16'),
    ('16-year-old'),
    ('16y'),
    ('16years'),
    ('16yo'),
    ('17 year old'),
    ('17 year-old'),
    ('17 years old'),
    ('17 years'),
    ('17 yo'),
    ('17'),
    ('17-year-old'),
    ('17y'),
    ('17years'),
    ('17yo'),
    ('18'),
    ('311'),
    ('38'),
    ('4chan is for faggots'),
    ('5 year old'),
    ('5 year-old'),
    ('5 years old'),
    ('5 years'),
    ('5 yo'),
    ('5'),
    ('5-year-old'),
    ('50 suicide attempts'),
    ('5y'),
    ('5years'),
    ('5yo'),
    ('6 year old'),
    ('6 year-old'),
    ('6 years old'),
    ('6 years'),
    ('6 yo'),
    ('6'),
    ('6-year-old'),
    ('6y'),
    ('6years'),
    ('6yo'),
    ('7 year old'),
    ('7 year-old'),
    ('7 years old'),
    ('7 years'),
    ('7 yo'),
    ('7'),
    ('7-year-old'),
    ('7y'),
    ('7years'),
    ('7yo'),
    ('8 year old'),
    ('8 year-old'),
    ('8 years old'),
    ('8 years'),
    ('8 yo'),
    ('8'),
    ('8-year-old'),
    ('88'),
    ('8y'),
    ('8years'),
    ('8yo'),
    ('9 year old'),
    ('9 year-old'),
    ('9 years old'),
    ('9 years'),
    ('9 yo'),
    ('9'),
    ('9-year-old'),
    ('9y'),
    ('9years'),
    ('9yo'),
    ('a10 aryan'),
    ('abuse me'),
    ('abuser'),
    ('abusive'),
    ('adolf hitler'),
    ('age gap'),
    ('age play'),
    ('age regress'),
    ('age regressor'),
    ('agere'),
    ('allah akbar'),
    ('allah is a jew'),
    ('allahu akbar'),
    ('alt faggot'),
    ('among us rape'),
    ('animal abuse'),
    ('anti-faggotry'),
    ('anti-lgbtq'),
    ('anti-lgbtqiap'),
    ('are you hanging yourself'),
    ('aryan emperor'),
    ('aryan jihad'),
    ('aryan'),
    ('aryans'),
    ('aryanx'),
    ('asian beater'),
    ('assbeater420'),
    ('assisted suicide'),
    ('autistic fag boyfriend'),
    ('autistic faggot'),
    ('azur lane faggot'),
    ('beaner'),
    ('beat me to death'),
    ('beating up minorities'),
    ('bestiality'),
    ('billions must die'),
    ('black people beater'),
    ('boy rapist'),
    ('boykisser'),
    ('brown people beater'),
    ('brown racist'),
    ('bug beater'),
    ('bug killer'),
    ('bug people beater'),
    ('buying drugs'),
    ('certified minor'),
    ('child abuse'),
    ('child lover'),
    ('child porn'),
    ('child rape'),
    ('child rapist'),
    ('child trafficker'),
    ('child traficker'),
    ('chill pedo vibes'),
    ('chink beater'),
    ('chink hater'),
    ('chink'),
    ('chinks'),
    ('coal burner'),
    ('coal burners'),
    ('coalburner'),
    ('coalburners'),
    ('consensual rape'),
    ('contradictory faggot'),
    ('coon'),
    ('coons'),
    ('cotton picker'),
    ('cunny archive'),
    ('cunny cumdump'),
    ('cunny rape'),
    ('cunny'),
    ('cunnyborea'),
    ('cunnyseur'),
    ('cut me'),
    ('cute and funny'),
    ('cutter'),
    ('death to america'),
    ('death to israel'),
    ('deport asians'),
    ('deport black people'),
    ('deport blacks'),
    ('deport brown people'),
    ('deport buddhists'),
    ('deport bug people'),
    ('deport bugs'),
    ('deport chinks'),
    ('deport christianity'),
    ('deport christians'),
    ('deport coons'),
    ('deport faggots'),
    ('deport fags'),
    ('deport filipinas'),
    ('deport filipino people'),
    ('deport filipinos'),
    ('deport flips'),
    ('deport gays'),
    ('deport hinduim'),
    ('deport hindus'),
    ('deport india'),
    ('deport indians'),
    ('deport irish "people"'),
    ('deport irish people'),
    ('deport islam'),
    ('deport israel'),
    ('deport jewish people'),
    ('deport jews'),
    ('deport judaism'),
    ('deport kikes'),
    ('deport latinos'),
    ('deport lgbtq'),
    ('deport loli'),
    ('deport men'),
    ('deport mexicans'),
    ('deport minorities'),
    ('deport mormons'),
    ('deport muslims'),
    ('deport my faggot life'),
    ('deport nazis'),
    ('deport niggers'),
    ('deport nigs'),
    ('deport norway'),
    ('deport pakis'),
    ('deport palestine'),
    ('deport quebec'),
    ('deport queers'),
    ('deport the fags'),
    ('deport trannies'),
    ('deport white people'),
    ('deport whites'),
    ('deport women'),
    ('die nazis die'),
    ('die retard die'),
    ('domestic abuse'),
    ('don''t be trans'),
    ('dothead'),
    ('drug dealer'),
    ('dukys'),
    ('edtwt users kys'),
    ('eight year old'),
    ('eight year-old'),
    ('eight years old'),
    ('eight yo'),
    ('eight-year-old'),
    ('eleven year old'),
    ('eleven year-old'),
    ('eleven years old'),
    ('eleven-year-old'),
    ('elliot rodger'),
    ('elliot-rodger'),
    ('emitting faggot vibes'),
    ('eslpedonigger'),
    ('esoteric hitlerism'),
    ('esoteric neo-aryan hitlerist'),
    ('ethical rapist'),
    ('evilcunnygang'),
    ('faaaaaggot'),
    ('fag beater'),
    ('fag hater'),
    ('fag'),
    ('fagdyke'),
    ('faggot beater'),
    ('faggot hater'),
    ('faggot jackass'),
    ('faggot'),
    ('faggotkitty'),
    ('faggotoid'),
    ('faggots'),
    ('fagism'),
    ('fatphobic'),
    ('fictohitler'),
    ('fifteen year old'),
    ('fifteen year-old'),
    ('fifteen years old'),
    ('fifteen yo'),
    ('fifteen-year-old'),
    ('filipina beater'),
    ('filipino beater'),
    ('filipino people beater'),
    ('five year old'),
    ('five year-old'),
    ('five years old'),
    ('five yo'),
    ('five-year-old'),
    ('flip beater'),
    ('former rapist'),
    ('fourteen year old'),
    ('fourteen year-old'),
    ('fourteen years old'),
    ('fourteen yo'),
    ('fourteen-year-old'),
    ('fratricide'),
    ('fuck asians'),
    ('fuck black people'),
    ('fuck blacks'),
    ('fuck brown people'),
    ('fuck buddhists'),
    ('fuck bug people'),
    ('fuck bugs'),
    ('fuck chinks'),
    ('fuck christianity'),
    ('fuck christians'),
    ('fuck coons'),
    ('fuck faggots'),
    ('fuck fags'),
    ('fuck filipinas'),
    ('fuck filipino people'),
    ('fuck filipinos'),
    ('fuck flips'),
    ('fuck gays'),
    ('fuck hinduim'),
    ('fuck hinduims'),
    ('fuck hindus'),
    ('fuck india'),
    ('fuck indians'),
    ('fuck irish "people"'),
    ('fuck irish people'),
    ('fuck islam'),
    ('fuck israel'),
    ('fuck jewish people'),
    ('fuck jews'),
    ('fuck judaism'),
    ('fuck kikes'),
    ('fuck latinos'),
    ('fuck lgbtq'),
    ('fuck loli'),
    ('fuck men'),
    ('fuck mexicans'),
    ('fuck minorities'),
    ('fuck mormons'),
    ('fuck muslims'),
    ('fuck my faggot life'),
    ('fuck my pathetic nigger life'),
    ('fuck nazis'),
    ('fuck niggers'),
    ('fuck nigs'),
    ('fuck norway'),
    ('fuck pakis'),
    ('fuck palestine'),
    ('fuck quebec'),
    ('fuck queers'),
    ('fuck the fags'),
    ('fuck trannies'),
    ('fuck ukraine'),
    ('fuck white people'),
    ('fuck whites'),
    ('fuck women'),
    ('fuck you kys'),
    ('fuck you nigger'),
    ('fuck zipperheads'),
    ('fucking faggot'),
    ('furry loli'),
    ('furry shota'),
    ('gang rape'),
    ('gas jew'),
    ('gas jews'),
    ('gay beater'),
    ('gay faggot'),
    ('gay hater'),
    ('gay shota'),
    ('gaynigger retard gang'),
    ('genocide'),
    ('getting raped'),
    ('gf beater'),
    ('girl friend beater'),
    ('girlfaggot'),
    ('girlfailure abuser'),
    ('girlfriend beater'),
    ('globalist'),
    ('gook'),
    ('gooks'),
    ('gore'),
    ('gorecore'),
    ('gothic lolita'),
    ('grapist'),
    ('groom me please'),
    ('groomable'),
    ('groomed child'),
    ('groomer'),
    ('guro lolita'),
    ('hail hitler'),
    ('hail victory'),
    ('hang myself'),
    ('hang yourself'),
    ('hate chinks'),
    ('hate faggots'),
    ('hate fags'),
    ('hate gays'),
    ('hate islam'),
    ('hate jews'),
    ('hate kikes'),
    ('hate lgbt'),
    ('hate lgbtq'),
    ('hate lgbtqia'),
    ('hate lgbtqqip2saa'),
    ('hate lgbttqqiaap'),
    ('hate loli'),
    ('hate men'),
    ('hate minorities'),
    ('hate muslims'),
    ('hate niggers'),
    ('hate nigs'),
    ('hate queers'),
    ('hate trannies'),
    ('hate women'),
    ('heil hitler'),
    ('heil victory'),
    ('hezbollah'),
    ('highschooler'),
    ('hilariously racist'),
    ('hitler daughter'),
    ('hitler did nothing wrong'),
    ('hitler enjoyer'),
    ('hitler youth'),
    ('hitler''s top guy'),
    ('hitler'),
    ('hitlerchildrape1488'),
    ('hitlerchungus'),
    ('hitlercunnyrape1488'),
    ('homicide'),
    ('homophobic'),
    ('husband beater'),
    ('i abuse men'),
    ('i abuse women'),
    ('i am 10 years old'),
    ('i am 10 years'),
    ('i am 10'),
    ('i am 11 years old'),
    ('i am 12 years old'),
    ('i am 12 years'),
    ('i am 12'),
    ('i am 13 years old'),
    ('i am 13 years'),
    ('i am 13'),
    ('i am 14 years old'),
    ('i am 14 years'),
    ('i am 14'),
    ('i am 15 years old'),
    ('i am 15 years'),
    ('i am 15'),
    ('i am 16 years old'),
    ('i am 16 years'),
    ('i am 16'),
    ('i am 17 years old'),
    ('i am 17 years'),
    ('i am 17'),
    ('i am 5 years old'),
    ('i am 5 years'),
    ('i am 5'),
    ('i am 6 years old'),
    ('i am 6 years'),
    ('i am 6'),
    ('i am 7 years old'),
    ('i am 7 years'),
    ('i am 7'),
    ('i am 8 years old'),
    ('i am 8 years'),
    ('i am 8'),
    ('i am 9 years old'),
    ('i am 9 years'),
    ('i am 9'),
    ('i am a 10 year old'),
    ('i am a 10 year-old'),
    ('i am a 10 yo'),
    ('i am a 11 year old'),
    ('i am a 11 year-old'),
    ('i am a 12 year old'),
    ('i am a 12 year-old'),
    ('i am a 12 yo'),
    ('i am a 13 year old'),
    ('i am a 13 year-old'),
    ('i am a 13 yo'),
    ('i am a 14 year old'),
    ('i am a 14 year-old'),
    ('i am a 14 yo'),
    ('i am a 15 year old'),
    ('i am a 15 year-old'),
    ('i am a 15 yo'),
    ('i am a 16 year old'),
    ('i am a 16 year-old'),
    ('i am a 16 yo'),
    ('i am a 17 year old'),
    ('i am a 17 year-old'),
    ('i am a 17 yo'),
    ('i am a 5 year old'),
    ('i am a 5 year-old'),
    ('i am a 5 yo'),
    ('i am a 6 year old'),
    ('i am a 6 year-old'),
    ('i am a 6 yo'),
    ('i am a 7 year old'),
    ('i am a 7 year-old'),
    ('i am a 7 yo'),
    ('i am a 8 year old'),
    ('i am a 8 year-old'),
    ('i am a 8 yo'),
    ('i am a 9 year old'),
    ('i am a 9 year-old'),
    ('i am a 9 yo'),
    ('i am a eight year old'),
    ('i am a eight year-old'),
    ('i am a fifteen year old'),
    ('i am a fifteen year-old'),
    ('i am a fifteen yo'),
    ('i am a five year old'),
    ('i am a five year-old'),
    ('i am a five yo'),
    ('i am a fourteen year old'),
    ('i am a fourteen year-old'),
    ('i am a fourteen yo'),
    ('i am a nine year old'),
    ('i am a nine year-old'),
    ('i am a nine yo'),
    ('i am a rapist'),
    ('i am a seven year old'),
    ('i am a seven year-old'),
    ('i am a seven yo'),
    ('i am a seventeen year old'),
    ('i am a seventeen year-old'),
    ('i am a seventeen yo'),
    ('i am a sex offender'),
    ('i am a six year old'),
    ('i am a six year-old'),
    ('i am a six yo'),
    ('i am a sixteen year old'),
    ('i am a sixteen year-old'),
    ('i am a sixteen yo'),
    ('i am a ten year old'),
    ('i am a ten year-old'),
    ('i am a ten yo'),
    ('i am a thirteen year old'),
    ('i am a thirteen year-old'),
    ('i am a thirteen yo'),
    ('i am a twelve year old'),
    ('i am a twelve year-old'),
    ('i am a twelve yo'),
    ('i am an 8 year old'),
    ('i am an 8 year-old'),
    ('i am an 8 yo'),
    ('i am an eight yo'),
    ('i am an eleven year old'),
    ('i am an eleven year-old'),
    ('i am eight years old'),
    ('i am eleven years old'),
    ('i am fifteen years old'),
    ('i am five years old'),
    ('i am fourteen years old'),
    ('i am going bash your head in with a rock'),
    ('i am hanging myself'),
    ('i am nine years old'),
    ('i am not a rapist anymore'),
    ('i am not a rapist'),
    ('i am seven years old'),
    ('i am seventeen years old'),
    ('i am six years old'),
    ('i am sixteen years old'),
    ('i am ten years old'),
    ('i am thirteen years old'),
    ('i am twelve years old'),
    ('i beat women'),
    ('i blame the jews'),
    ('i cut myself'),
    ('i don''t like rape'),
    ('i dont like rape'),
    ('i enjoy rape'),
    ('i enjoy raping you'),
    ('i enjoy raping'),
    ('i fucking hate asians'),
    ('i fucking hate black people'),
    ('i fucking hate blacks'),
    ('i fucking hate brown people'),
    ('i fucking hate bug people'),
    ('i fucking hate bugs'),
    ('i fucking hate chinks'),
    ('i fucking hate faggots'),
    ('i fucking hate fags'),
    ('i fucking hate filipinas'),
    ('i fucking hate filipino people'),
    ('i fucking hate filipinos'),
    ('i fucking hate flips'),
    ('i fucking hate gays'),
    ('i fucking hate indians'),
    ('i fucking hate irish "people"'),
    ('i fucking hate irish people'),
    ('i fucking hate islam'),
    ('i fucking hate jews'),
    ('i fucking hate kikes'),
    ('i fucking hate latinos'),
    ('i fucking hate loli'),
    ('i fucking hate men'),
    ('i fucking hate mexicans'),
    ('i fucking hate minorities'),
    ('i fucking hate muslims'),
    ('i fucking hate nazis'),
    ('i fucking hate niggers'),
    ('i fucking hate nigs'),
    ('i fucking hate pakis'),
    ('i fucking hate queers'),
    ('i fucking hate trannies'),
    ('i fucking hate white people'),
    ('i fucking hate whites'),
    ('i fucking hate women'),
    ('i fucking hate zipperheads'),
    ('i hate asians'),
    ('i hate black people'),
    ('i hate blacks'),
    ('i hate brown people'),
    ('i hate bug people'),
    ('i hate bugs'),
    ('i hate chinks'),
    ('i hate faggots'),
    ('i hate fags'),
    ('i hate filipinas'),
    ('i hate filipino people'),
    ('i hate filipinos'),
    ('i hate flips'),
    ('i hate gays'),
    ('i hate indians'),
    ('i hate irish "people"'),
    ('i hate irish people'),
    ('i hate islam'),
    ('i hate jews'),
    ('i hate kikes'),
    ('i hate latinos'),
    ('i hate lgbt'),
    ('i hate lgbtq'),
    ('i hate lgbtqia'),
    ('i hate lgbtqqip2saa'),
    ('i hate lgbttqqiaap'),
    ('i hate loli'),
    ('i hate men'),
    ('i hate mexicans'),
    ('i hate minorities'),
    ('i hate muslims'),
    ('i hate nazis'),
    ('i hate niggers'),
    ('i hate nigs'),
    ('i hate pakis'),
    ('i hate queers'),
    ('i hate trannies'),
    ('i hate white people'),
    ('i hate whites'),
    ('i hate women'),
    ('i hate zipperheads'),
    ('i kill people'),
    ('i let my ex beat me for fun'),
    ('i love gore'),
    ('i love israel gon'),
    ('i love loli'),
    ('i love minors'),
    ('i love nazi'),
    ('i love nazis'),
    ('i love shota'),
    ('i love shotacon'),
    ('i must rape'),
    ('i rape twinks'),
    ('i should kms'),
    ('i want to be groomed'),
    ('i will beat the shit out of you'),
    ('i will beat you with a rock'),
    ('i will hang myself while drunk'),
    ('i will hang myself'),
    ('i will kill myself in front of you'),
    ('i will kill myself on vc infront of you'),
    ('i will kill myself'),
    ('i will rape women'),
    ('i will rape you'),
    ('i will rape'),
    ('i will sexually assault you'),
    ('i''ll kill myself'),
    ('i''m 10'),
    ('i''m 12'),
    ('i''m 13'),
    ('i''m 14'),
    ('i''m 15'),
    ('i''m 16'),
    ('i''m 17'),
    ('i''m 5'),
    ('i''m 6'),
    ('i''m 7'),
    ('i''m 8'),
    ('i''m 9'),
    ('i''m a 10 year old'),
    ('i''m a 10 year-old'),
    ('i''m a 10 yo'),
    ('i''m a 11 year old'),
    ('i''m a 11 year-old'),
    ('i''m a 12 year old'),
    ('i''m a 12 year-old'),
    ('i''m a 12 yo'),
    ('i''m a 13 year old'),
    ('i''m a 13 year-old'),
    ('i''m a 13 yo'),
    ('i''m a 14 year old'),
    ('i''m a 14 year-old'),
    ('i''m a 14 yo'),
    ('i''m a 15 year old'),
    ('i''m a 15 year-old'),
    ('i''m a 15 yo'),
    ('i''m a 16 year old'),
    ('i''m a 16 year-old'),
    ('i''m a 16 yo'),
    ('i''m a 17 year old'),
    ('i''m a 17 year-old'),
    ('i''m a 17 yo'),
    ('i''m a 5 year old'),
    ('i''m a 5 year-old'),
    ('i''m a 5 yo'),
    ('i''m a 6 year old'),
    ('i''m a 6 year-old'),
    ('i''m a 6 yo'),
    ('i''m a 7 year old'),
    ('i''m a 7 year-old'),
    ('i''m a 7 yo'),
    ('i''m a 8 year old'),
    ('i''m a 8 year-old'),
    ('i''m a 8 yo'),
    ('i''m a 9 year old'),
    ('i''m a 9 year-old'),
    ('i''m a 9 yo'),
    ('i''m a eight year old'),
    ('i''m a eight year-old'),
    ('i''m a fifteen year old'),
    ('i''m a fifteen year-old'),
    ('i''m a fifteen yo'),
    ('i''m a five year old'),
    ('i''m a five year-old'),
    ('i''m a five yo'),
    ('i''m a fourteen year old'),
    ('i''m a fourteen year-old'),
    ('i''m a fourteen yo'),
    ('i''m a nine year old'),
    ('i''m a nine year-old'),
    ('i''m a nine yo'),
    ('i''m a rapist'),
    ('i''m a serial rapist'),
    ('i''m a seven year old'),
    ('i''m a seven year-old'),
    ('i''m a seven yo'),
    ('i''m a seventeen year old'),
    ('i''m a seventeen year-old'),
    ('i''m a seventeen yo'),
    ('i''m a sex offender'),
    ('i''m a six year old'),
    ('i''m a six year-old'),
    ('i''m a six yo'),
    ('i''m a sixteen year old'),
    ('i''m a sixteen year-old'),
    ('i''m a sixteen yo'),
    ('i''m a ten year old'),
    ('i''m a ten year-old'),
    ('i''m a ten yo'),
    ('i''m a thirteen year old'),
    ('i''m a thirteen year-old'),
    ('i''m a thirteen yo'),
    ('i''m a twelve year old'),
    ('i''m a twelve year-old'),
    ('i''m a twelve yo'),
    ('i''m against rape because kids are born'),
    ('i''m an eight yo'),
    ('i''m an eleven year old'),
    ('i''m an eleven year-old'),
    ('i''m not a rapist anymore'),
    ('i''m not a rapist'),
    ('im gonna kms'),
    ('incest'),
    ('indian beater'),
    ('infanticide'),
    ('irish "people" beater'),
    ('irish people beater'),
    ('irl loli'),
    ('irl shota'),
    ('ironic rape'),
    ('ironicrape'),
    ('isil'),
    ('isis'),
    ('islam beater'),
    ('islam hater'),
    ('islamic state'),
    ('islamophobic'),
    ('israel defence force'),
    ('israel defense force'),
    ('israeli defence force'),
    ('israeli defense force'),
    ('israeli revenue service'),
    ('its probably the jews'),
    ('jailbait'),
    ('jerusalem hate'),
    ('jew beater'),
    ('jew hate'),
    ('jew hater'),
    ('jew jitsu'),
    ('jewish hate foundation'),
    ('jews'),
    ('just beat the shit out of me'),
    ('kekistan vs israel'),
    ('kiddie fiddler'),
    ('kike beater'),
    ('kike hater'),
    ('kike'),
    ('kikes'),
    ('kikistan vs israel'),
    ('kill all asians'),
    ('kill all black people'),
    ('kill all blacks'),
    ('kill all brown people'),
    ('kill all bug people'),
    ('kill all bugs'),
    ('kill all chinks'),
    ('kill all faggots'),
    ('kill all fags'),
    ('kill all filipinas'),
    ('kill all filipino people'),
    ('kill all filipinos'),
    ('kill all flips'),
    ('kill all gays'),
    ('kill all indians'),
    ('kill all irish "people"'),
    ('kill all irish people'),
    ('kill all islam'),
    ('kill all jews'),
    ('kill all kikes'),
    ('kill all latinos'),
    ('kill all loli'),
    ('kill all men'),
    ('kill all mexicans'),
    ('kill all minorities'),
    ('kill all muslims'),
    ('kill all nazis'),
    ('kill all niggers'),
    ('kill all nigs'),
    ('kill all pakis'),
    ('kill all queers'),
    ('kill all trannies'),
    ('kill all white people'),
    ('kill all whites'),
    ('kill all women'),
    ('kill all zipperheads'),
    ('kill arabs'),
    ('kill asians'),
    ('kill black people'),
    ('kill blacks'),
    ('kill brown people'),
    ('kill bug people'),
    ('kill bugs'),
    ('kill chinks'),
    ('kill everyone'),
    ('kill faggots'),
    ('kill fags'),
    ('kill fat people'),
    ('kill filipino people'),
    ('kill flips'),
    ('kill for me'),
    ('kill gays'),
    ('kill homeless people'),
    ('kill indians'),
    ('kill irish "people"'),
    ('kill irish people'),
    ('kill islam'),
    ('kill jews'),
    ('kill kikes'),
    ('kill kill kill'),
    ('kill latinos'),
    ('kill lgbt'),
    ('kill lgbtq'),
    ('kill lgbtqia'),
    ('kill lgbtqqip2saa'),
    ('kill lgbttqqiaap'),
    ('kill loli'),
    ('kill men'),
    ('kill mexicans'),
    ('kill minorities'),
    ('kill muslims'),
    ('kill nazis'),
    ('kill nigg'),
    ('kill niggers with rocks'),
    ('kill niggers'),
    ('kill niggs'),
    ('kill nigs'),
    ('kill pakis'),
    ('kill people'),
    ('kill queers'),
    ('kill the chinks'),
    ('kill the faggots'),
    ('kill the fags'),
    ('kill the gays'),
    ('kill the jews'),
    ('kill the kikes'),
    ('kill the men'),
    ('kill the minorities'),
    ('kill the muslims'),
    ('kill the niggers'),
    ('kill the nigs'),
    ('kill the queers'),
    ('kill the trannies'),
    ('kill the women'),
    ('kill trannies'),
    ('kill white people'),
    ('kill whites'),
    ('kill with hammer'),
    ('kill women'),
    ('kill yourself'),
    ('kill zipperheads'),
    ('kill'),
    ('killed'),
    ('killer'),
    ('killfatpeople'),
    ('killing mself'),
    ('killing myself at 25'),
    ('killing myself at 40'),
    ('killing myself'),
    ('killing people with rocks'),
    ('killing people'),
    ('killing ppl w a rock'),
    ('killing'),
    ('kills people'),
    ('kinda a fag'),
    ('Kiwi Farms'),
    ('kkk'),
    ('kms'),
    ('knife play'),
    ('knifeplay'),
    ('kool kids klub'),
    ('ku klux klan'),
    ('kys'),
    ('latino beater'),
    ('let''s kill people'),
    ('lgbtq hater'),
    ('literally hitler'),
    ('lithuainan suicide enjoyer'),
    ('lithuania suicide enjoyer'),
    ('little rape slux'),
    ('loli beater'),
    ('loli furry'),
    ('loli in early 20s'),
    ('loli rape'),
    ('loli'),
    ('lolicon lerix'),
    ('lolicon''s fucking disgusting'),
    ('lolicon''s fucking gross'),
    ('lolicon'),
    ('lolicore'),
    ('lolisho'),
    ('lolita fashion'),
    ('lolita'),
    ('man hater'),
    ('map'),
    ('mass shooter fan club'),
    ('mass shooter'),
    ('matricide'),
    ('max prestige faggot'),
    ('men beater'),
    ('mexican beater'),
    ('might be a pedo'),
    ('might be racist'),
    ('mildly racist'),
    ('minor attracted person'),
    ('minor attracted persons'),
    ('minor minor minor minor minor minor minor'),
    ('minor minor minor minor minor minor'),
    ('minor minor minor minor minor'),
    ('minor minor minor minor'),
    ('minor minor minor'),
    ('minor minor'),
    ('minor'),
    ('minor-attracted person'),
    ('minor-attracted persons'),
    ('minority beater'),
    ('minority hater'),
    ('minorminor'),
    ('minorminorminor'),
    ('minorminorminorminor'),
    ('minorminorminorminorminor'),
    ('minorminorminorminorminorminor'),
    ('minorminorminorminorminorminorminor'),
    ('minors'),
    ('misogynist'),
    ('mnsfw'),
    ('mnwo'),
    ('moralfags kys'),
    ('most racist man alive'),
    ('mr suicide sheep'),
    ('mrsuicidesheep'),
    ('mudslime'),
    ('mudslimes'),
    ('murder murder kill kill'),
    ('murder trannies'),
    ('muslim beater'),
    ('muslim hater'),
    ('nate higgers'),
    ('national socialism'),
    ('nato tranny'),
    ('nazi beater'),
    ('nazi leader'),
    ('nazi'),
    ('necrophile'),
    ('neega'),
    ('neeger'),
    ('neo nazi'),
    ('neo-nazi'),
    ('nig beater'),
    ('nig hater'),
    ('nig'),
    ('nigg'),
    ('nigga hater'),
    ('nigga'),
    ('niggah'),
    ('niggarapist'),
    ('nigger beater'),
    ('nigger faggot'),
    ('nigger hater'),
    ('nigger rapist'),
    ('nigger'),
    ('niggerfaggot'),
    ('niggerlicious'),
    ('niggers'),
    ('niggger'),
    ('niggot'),
    ('niggress'),
    ('niggy'),
    ('nigs'),
    ('nine year old'),
    ('nine year-old'),
    ('nine years old'),
    ('nine yo'),
    ('nine-year-old'),
    ('nonconsensual hand holding'),
    ('not 18'),
    ('not a fan of trans personally'),
    ('not a paedophile'),
    ('not a pedophile'),
    ('not over 18'),
    ('not suicidal'),
    ('not trans'),
    ('nuke africa'),
    ('nuke china'),
    ('nuke israel'),
    ('onlyfans'),
    ('op is a faggot'),
    ('osama bin laden'),
    ('paedo'),
    ('paedokiller'),
    ('paedophile'),
    ('paedophiles'),
    ('pajeet'),
    ('pajeets'),
    ('paki beater'),
    ('paki'),
    ('pakkis'),
    ('paraphile'),
    ('patricide'),
    ('pattern noticer'),
    ('pdf file'),
    ('pedbait'),
    ('pedo'),
    ('pedokiller'),
    ('pedomom'),
    ('pedophile'),
    ('pedophiles'),
    ('pedophilia'),
    ('pedos kys'),
    ('pedoslut'),
    ('pervert degenerate faggot'),
    ('petplay'),
    ('piss'),
    ('pissfaggot'),
    ('please hang yourself'),
    ('please kill yourself'),
    ('please rape me'),
    ('please rape my face'),
    ('pls hit me and abuse me'),
    ('potential mass shooter'),
    ('ppl saying nigga instead of nigger cucks'),
    ('ppls saying nigga instead of nigger suck'),
    ('prevert degenerate faggot'),
    ('pro faggotry'),
    ('prostitute'),
    ('q'),
    ('queer beater'),
    ('queer hater'),
    ('race war now'),
    ('racism inc'),
    ('racism is funny'),
    ('racism'),
    ('racist as a joke'),
    ('racist minority'),
    ('racist'),
    ('racists kys'),
    ('radfemhitler fan club'),
    ('rag head'),
    ('rag heads'),
    ('raghead'),
    ('ragheads'),
    ('rape bunny'),
    ('rape in india today'),
    ('rape in india'),
    ('rape isn''t real'),
    ('rape israel'),
    ('rape me'),
    ('rape men'),
    ('rape music'),
    ('rape my face'),
    ('rape people'),
    ('rape play'),
    ('rape survivor'),
    ('rape suvivor'),
    ('rape victim'),
    ('rape women'),
    ('rape'),
    ('rapebastard club'),
    ('rapebutnotinanindianway'),
    ('raped'),
    ('rapefag'),
    ('rapeman'),
    ('rapemaxxing'),
    ('rapemeat'),
    ('raper'),
    ('rapes people'),
    ('rapes'),
    ('rapetoy'),
    ('raping'),
    ('rapist homo thug'),
    ('rapist'),
    ('rapists'),
    ('respect niggers'),
    ('retard'),
    ('retarded faggot'),
    ('retarded nigger'),
    ('roastie'),
    ('roasty'),
    ('romantic woman beater'),
    ('sandnigger'),
    ('say you love me or i will kill myself'),
    ('school shooter'),
    ('self harm'),
    ('self-harm'),
    ('selfharm'),
    ('seller'),
    ('selling drugs'),
    ('selling'),
    ('seppo'),
    ('seppos'),
    ('serial killer'),
    ('seven year old'),
    ('seven year-old'),
    ('seven years old'),
    ('seven yo'),
    ('seven-year-old'),
    ('seventeen year old'),
    ('seventeen year-old'),
    ('seventeen years old'),
    ('seventeen yo'),
    ('seventeen-year-old'),
    ('sex offender'),
    ('sexual assault victim'),
    ('sexual assault'),
    ('sexually assaults you'),
    ('shota lover'),
    ('shota raper'),
    ('shota'),
    ('shotabait'),
    ('shotacon'),
    ('should die'),
    ('should kill self'),
    ('shtwt'),
    ('sieg heil'),
    ('six year old'),
    ('six year-old'),
    ('six years old'),
    ('six yo'),
    ('six-year-old'),
    ('sixteen year old'),
    ('sixteen year-old'),
    ('sixteen years old'),
    ('sixteen yo'),
    ('sixteen-year-old'),
    ('skinny nigger'),
    ('slave owner club'),
    ('slightly racist'),
    ('snuff'),
    ('sororicide'),
    ('SoyjackParty'),
    ('soyjak party'),
    ('spic'),
    ('spouse beater'),
    ('straight shota'),
    ('stupid faggot little cocksucker'),
    ('suicidal tendencies'),
    ('suicidal'),
    ('suicide bomber'),
    ('suicide boy'),
    ('suicide boys'),
    ('suicide by boeing'),
    ('suicide idealizer'),
    ('suicide in 3 months'),
    ('suicide might be the right option for you'),
    ('suicide room'),
    ('suicide watch'),
    ('suicide'),
    ('supreme gentleman'),
    ('supreme-gentleman'),
    ('talmud denouncer'),
    ('teen suicide'),
    ('ten year old'),
    ('ten year-old'),
    ('ten years old'),
    ('ten yo'),
    ('ten-year-old'),
    ('terf'),
    ('thirteen year old'),
    ('thirteen year-old'),
    ('thirteen years old'),
    ('thirteen yo'),
    ('thirteen-year-old'),
    ('this faggot can throw hands'),
    ('thug rape'),
    ('tkd'),
    ('tnd'),
    ('total kike victory'),
    ('total nigger life'),
    ('touch me without consent'),
    ('towel head'),
    ('towel heads'),
    ('towelhead'),
    ('towelheads'),
    ('trannie beater'),
    ('trannies are made up'),
    ('trannies'),
    ('tranny hater'),
    ('tranny'),
    ('trannyism'),
    ('transphobe'),
    ('transphobic'),
    ('troon'),
    ('Troonphobic'),
    ('twelve year old'),
    ('twelve year-old'),
    ('twelve years old'),
    ('twelve yo'),
    ('twelve-year-old'),
    ('twink beater'),
    ('twinkbeater'),
    ('twitter niggers kys'),
    ('under 18'),
    ('under age'),
    ('under aged'),
    ('under eighteen'),
    ('underage'),
    ('underaged'),
    ('uoh'),
    ('UOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOH'),
    ('verbal abuse'),
    ('violencepilled'),
    ('virgin suicide'),
    ('white beater'),
    ('white people beater'),
    ('white power'),
    ('white pride'),
    ('white supremacy'),
    ('wife beater'),
    ('will hang myself while drunk'),
    ('will kill myself on vc infront of you'),
    ('will kill myself'),
    ('woman beater'),
    ('woman hater'),
    ('women beater'),
    ('you hate me because i was raped'),
    ('you should hang myself'),
    ('you should hang yourself'),
    ('you should kill yourself now'),
    ('you should kill yourself'),
    ('ywnbaw'),
    ('zionist'),
    ('zipperhead beater'),
    ('zipperhead'),
    ('zipperheads'),
    ('zoophile')
ON CONFLICT (name) DO NOTHING;

DELETE FROM
    club
USING
    banned_club
WHERE
    LOWER(club.name) = banned_club.name;
