ALTER TABLE IF EXISTS inbox
    ADD COLUMN IF NOT EXISTS body TEXT;

ALTER TABLE IF EXISTS inbox
    ADD COLUMN IF NOT EXISTS direction mam_direction;

ALTER TABLE IF EXISTS inbox
    ALTER COLUMN content DROP NOT NULL;
