[mypy]
explicit_package_bases = true
plugins = pydantic.mypy

[mypy-dateutil.*]
ignore_missing_imports = True

[mypy-pillow_heif]
ignore_missing_imports = True

[mypy-pytricia]
ignore_missing_imports = True

[mypy-jwt]
ignore_missing_imports = True

[mypy-jwt.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True
