[mypy]
exclude = ^venv/
explicit_package_bases = true
disallow_untyped_defs = true
disallow_any_explicit = True

[mypy-duotypes]
disallow_any_explicit = False

[mypy-boto3]
ignore_missing_imports = True

[mypy-botocore.*]
ignore_missing_imports = True

[mypy-blurhash]
ignore_missing_imports = True

[mypy-confusable_homoglyphs.*]
ignore_missing_imports = True

[mypy-dateutil.*]
ignore_missing_imports = True

[mypy-onnxruntime]
ignore_missing_imports = True

[mypy-pillow_heif]
ignore_missing_imports = True

[mypy-spacy]
ignore_missing_imports = True

[mypy-spacy.*]
ignore_missing_imports = True

[mypy-pytricia]
ignore_missing_imports = True

[mypy-jwt]
ignore_missing_imports = True

[mypy-jwt.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True
