from antiabuse.normalize import verb_forms_for_each

profile = [
    "1488",
    "beaner",
    "cervix",
    "chink",
    "chinks",
    "coal burner",
    "coal burners",
    "cock",
    "coon",
    "cum",
    "cunny",
    "cunnypilled",
    "cutmaxxer",
    "cut myself",
    "cut ourselves",
    "cut yourself",
    "edtwt",
    "end my own life",
    "face fuck",
    "faggot",
    "faggots",
    "groom me",
    "heil hitler",
    "kike",
    "kikes",
    "killed myself",
    "killed yourself",
    "killing myself",
    "killing yourself",
    "kill myself",
    "kill yourself",
    "kms",
    "kys",
    "loli",
    "lolicon",
    "lolicons",
    "lolisho",
    "masterbation",
    "masturbation",
    "neggers",
    "neggress",
    "negress",
    "nibba",
    "nig",
    "niga",
    "nigga",
    "niggas",
    "nigge",
    "nigger",
    "niggerlicious",
    "niggers",
    "nigglet",
    "niggress",
    "niggu",
    "nigguh",
    "niggy",
    "niglet",
    "niglets",
    "nigs",
    "pajeet",
    "pajeets",
    "proshipper",
    "rapebait"
    "rapist",
    "rapists",
    "raype",
    "shit skin",
    "shota",
    "shotacon",
    "shotacons",
    "shtwt",
    "sieg heil",
    "throat pussy",
    "tkd",
    "tnd",
    "trannies",
    "tranny",
    "trannys",
    "troon",
    "troons",
    "you'll never be a woman",
    "you will never be a woman",
    "ywnbaw",
] + verb_forms_for_each([
    "dick",
    "masterbate",
    "masturbate",
    "self harm",
]) + verb_forms_for_each([
    "rape"
], exclude=['er', 'ers'])

display_name = list(profile)

occupation = list(profile)

education = list(profile)

solitication = [
    'cashapp',
    'finsub',
    'paypal',
    'telegram',
    'venmo',
    'zangi',
]


chat = [
    "1488",
    "about to bust",
    "abuse me",
    "abuse you",
    "ahole",
    "anal",
    "anally",
    "anus",
    "ass cheeks",
    "ass hole",
    "ass pics",
    "ass pounded",
    "back shots",
    "backshots",
    "ballsack",
    "bash your",
    "beaner",
    "beastial",
    "beastiality",
    "beat my meat",
    "bellend",
    "bend you over",
    "benis",
    "bestiality",
    "bewbies",
    "big pp",
    "bitch",
    "bj",
    "bjs",
    "blow job",
    "blow jobs",
    "blow your brains",
    "boobers",
    "boobies",
    "boobs",
    "breading me",
    "breading you",
    "breasts",
    "breedable",
    "breeding me",
    "breeding you",
    "breed me",
    "breed you",
    "bukkake",
    "bust a load",
    "bust a nut",
    "bust for you",
    "bust inside",
    "bust load",
    "bust loads",
    "bust on my",
    "bust on your",
    "bust ropes",
    "bust some ropes",
    "butt hole",
    "butt stuff",
    "bwc",
    "can I bust",
    "can I smash",
    "cawk",
    "cervix",
    "chink",
    "chinks",
    "clit",
    "clitoris",
    "cmm",
    "coal burner",
    "coal burners",
    "cock",
    "cockface",
    "cockhead",
    "cockmunch",
    "cockmuncher",
    "cocks",
    "cocksleeve",
    "condom",
    "cooch",
    "coom",
    "coon",
    "cooter",
    "coprophilia",
    "cuck",
    "cuckold",
    "cum",
    "cummies",
    "cumming",
    "cumms",
    "cummshot",
    "cums",
    "cumshot",
    "cumslut",
    "cunilingus",
    "cunillingus",
    "cunnilingus",
    "cunny",
    "cunnypilled",
    "cunt",
    "cunts",
    "cut herself",
    "cutmaxxer",
    "cut me",
    "cut myself",
    "cut my wrist",
    "cut my wrists",
    "cut ourselves",
    "cutting myself",
    "cutting yourself",
    "cut you",
    "cut your head",
    "cut your name",
    "cut your neck",
    "cut yourself",
    "cut your wrist",
    "cut your wrists",
    "dih",
    "dike",
    "dikes",
    "dildo",
    "dildos",
    "dog fucker",
    "doggin",
    "dogging",
    "do it raw",
    "dom",
    "dommy",
    "donger",
    "dongers",
    "down my throat",
    "eaten out",
    "eating you out",
    "eat me out",
    "eat my ass",
    "eat you out",
    "eat your ass",
    "eat your butt",
    "eat your guts",
    "🍇 ed",
    "edge me",
    "edge you",
    "edging",
    "edtwt",
    "end my own life",
    "end your life",
    "e sex",
    "fag",
    "faggitt",
    "faggot",
    "faggots",
    "fagot",
    "fags",
    "fanny flaps",
    "fart box",
    "fat ass",
    "feet on your",
    "felching",
    "fellate",
    "fellatio",
    "femdom",
    "fetish",
    "fingering",
    "finish in you",
    "finish in your",
    "finish on you",
    "finish on your",
    "foot job",
    "footjob",
    "foreskin",
    "fuckable",
    "fucking me",
    "fucking you",
    "fuck you",
    "fuck your",
    "fuck yourself",
    "fun bags",
    "gag me",
    "gag you",
    "gag your mouth",
    "gape",
    "gave me head",
    "gay sex",
    "genitalia",
    "genitals",
    "get piped",
    "getting piped",
    "gimme head",
    "give me head",
    "goatse",
    "going to bust",
    "golden shower",
    "gook",
    "gooks",
    "gooner",
    "gooners",
    "goonette",
    "goonettes",
    "gooning",
    "goonmaxxing",
    "goyish",
    "graped",
    "grape you",
    "graping",
    "groom me",
    "groom you",
    "hand job",
    "handjob",
    "hanged myself",
    "hanged yourself",
    "hanging myself",
    "hanging yourself",
    "hang myself",
    "hang yourself",
    "have my way",
    "head game",
    "healslut",
    "heil hitler",
    "his seed",
    "hit it from the back",
    "hit it raw",
    "ho",
    "hoe",
    "hoes",
    "homo",
    "honkers",
    "hornier",
    "horniest",
    "horny",
    "hotsex",
    "how tight are you",
    "how tight is it",
    "how tight it is",
    "incest",
    "🍇 ing",
    "inside of your guts",
    "inside you",
    "intercourse",
    "jack off",
    "jackoff",
    "jeet",
    "jeets",
    "jerked off",
    "jerking it",
    "jerking me off",
    "jerking off",
    "jerking you off",
    "jerk it off",
    "jerk me off",
    "jerk off",
    "jerk you off",
    "jewishly",
    "jism",
    "jiz",
    "jizm",
    "jizz",
    "kike",
    "kikes",
    "killed myself",
    "killed yourself",
    "killing myself",
    "killing yourself",
    "kill myself",
    "kill yourself",
    "kinky",
    "kms",
    "kys",
    "labia",
    "lemme hit",
    "lemme smash",
    "let me eat it",
    "lick my",
    "lick your",
    "like it raw",
    "likes it raw",
    "loli",
    "lolicon",
    "lolicons",
    "lolisho",
    "lube",
    "madarchod",
    "masterbation",
    "masturbation",
    "me eat your",
    "milkers",
    "milkies",
    "molest",
    "molestation",
    "molester",
    "molesting",
    "my load",
    "my loads",
    "my nuts",
    "my pp",
    "my throat",
    "necrophilia",
    "neggers",
    "neggress",
    "negress",
    "nibba",
    "nice ass",
    "nig",
    "niga",
    "nigga",
    "niggas",
    "nigge",
    "nigger",
    "niggerlicious",
    "niggers",
    "nigglet",
    "niggress",
    "niggu",
    "nigguh",
    "niggy",
    "niglet",
    "niglets",
    "nigs",
    "nipple",
    "nipples",
    "nut on my",
    "nut on those",
    "nut on your",
    "nutsack",
    "nut to them",
    "nut to your",
    "orgasim",
    "orgasims",
    "orgasm",
    "orgasmed",
    "orgasming",
    "orgasms",
    "orgy",
    "paedo",
    "paedophile",
    "pajeet",
    "pajeeta",
    "pajeetas",
    "pajeets",
    "paki",
    "pakis",
    "paraphilias",
    "peanitz",
    "pedo",
    "pedophile",
    "pedophilia",
    "pee on me",
    "pee on my",
    "pee on you",
    "pee on your",
    "pegged",
    "pegging",
    "penis",
    "penises",
    "penis fucker",
    "penus",
    "phonesex",
    "pin you",
    "piss",
    "pissflaps",
    "pissin",
    "pissing",
    "plow me",
    "plow my",
    "plow you",
    "plow your",
    "poojeet",
    "poojeeta",
    "poojeetas",
    "poojeets",
    "poop",
    "porn",
    "porno",
    "pornography",
    "pornos",
    "pound you",
    "pound your",
    "pp size",
    "pre cum",
    "prostitute",
    "pussies",
    "pussy",
    "pussys",
    "puta",
    "railing you",
    "rail you",
    "rapebait",
    "rapist",
    "rapists",
    "raw dog you",
    "raype",
    "ray ping",
    "ride me",
    "ride my cock",
    "ride my face",
    "ride my mouth",
    "ride my mustache",
    "ride my tongue",
    "ride you",
    "ride your cock",
    "ride your face",
    "ride your mouth",
    "ride your mustache",
    "ride your tongue",
    "rim job",
    "rimming",
    "rub my",
    "rub your",
    "ruin you",
    "scrote",
    "scrotum",
    "semen",
    "sex",
    "sextoy",
    "shag",
    "shagging",
    "shemale",
    "shit fuck",
    "shit in my",
    "shit in your",
    "shit on my",
    "shit on your",
    "shit skin",
    "shlong",
    "shota",
    "shotacon",
    "shotacons",
    "shtwt",
    "sieg heil",
    "sit on me",
    "sit on my face",
    "sit on your face",
    "skank",
    "slap me",
    "slap my",
    "slap you",
    "slap your",
    "slit my wrist",
    "slit my wrists",
    "slit your wrist",
    "slit your wrists",
    "sluts",
    "slutty",
    "small pp",
    "smegma",
    "sodomize",
    "sodomy",
    "some head",
    "sperm",
    "spic",
    "spit in my face",
    "spit in my mouth",
    "spit in your face",
    "spit in your mouth",
    "spit on me",
    "spit on my face",
    "spit on my mouth",
    "spit on you",
    "spit on your face",
    "spit on your mouth",
    "stabbed",
    "stabbing me",
    "stabbing you",
    "stab me",
    "stab you",
    "stab your",
    "step on me",
    "strangle me",
    "strangle you",
    "strap on",
    "stretch you",
    "stroke it",
    "stroking it",
    "suicidal",
    "suicide",
    "testicle",
    "that ass",
    "that pp",
    "their seed",
    "thighs",
    "thot",
    "throat pussy",
    "tiddies",
    "tiddy",
    "tie me",
    "tie you",
    "tiny pp",
    "tits",
    "titties",
    "titty",
    "tkd",
    "tnd",
    "to bust in",
    "to bust to",
    "to goon",
    "tongue punch",
    "to nut",
    "touch myself",
    "touch yourself",
    "tranner",
    "trannies",
    "tranny",
    "trannys",
    "troon",
    "troons",
    "tug job",
    "tugjob",
    "up the ass",
    "use me",
    "use my mouth",
    "use you",
    "use your mouth",
    "vagabunda",
    "vagina",
    "viagra",
    "vulva",
    "wanna fill you",
    "wanna fuck",
    "while I smash",
    "whore",
    "whores",
    "wincest",
    "🍇 you",
    "you are retarded",
    "you'll never be a woman",
    "your ass",
    "you retard",
    "you retarded",
    "your feet",
    "your hole",
    "your holes",
    "your insides",
    "your lips",
    "your pp",
    "your thigh",
    "your throat",
    "your toes",
    "your virginity",
    "your wrist",
    "your wrists",
    "you will never be a woman",
    "ywnbaw",
    "zoophilia",
] + verb_forms_for_each([
    "ass fuck",
    "butt fuck",
    "carpet munch",
    "cream pie",
    "deep throat",
    "dick",
    "ejaculate",
    "face fuck",
    "fanny fuck",
    "finger fuck",
    "finger lick",
    "fist lick",
    "gang bang",
    "impregnate",
    "masterbate",
    "masturbate",
    "self cut",
    "self harm",
    "slut",
    "throat fuck",
    "titty fuck",
    "titty wank",
    "tit wank",
    "wank",
]) + verb_forms_for_each([
    "choke",
    "rape",
    "rvpe",
], exclude=['er', 'ers'])
