import re
import unicodedata

# The idea of this list is to filter the most extreme and most common ways to
# offend in intros. Because it only applies to intros, we've aimed for broad
# terms that could be acceptable in an *established* conversations, but are
# typically socially unacceptable at the start of a conversation.
#
# Although the list is likely to change over time, it probably won't change
# very frequently, so we'll just hardcode it rather than storing it in the DB.



# Used to convert slang in an input string to a more standard form so that it's
# easier to detect coarse language later on
_normalization_map = {
    "b": "be",
    "btch": "bitch",
    "c+u+m+": "cum",
    "c+v+m+": "cum",
    "c0ck": "cock",
    "c0cksucker": "cocksucker",
    "cvmming": "cumming",
    "cvms": "cums",
    "cvmshot": "cumshot",
    "fck": "fuck",
    "fcked": "fucked",
    "fcking": "fucking",
    "fk": "fuck",
    "fked": "fucked",
    "fking": "fucking",
    "fuckin": "fucking",
    "fuk": "fuck",
    "fuked": "fucked",
    "fuking": "fucking",
    "fvck": "fuck",
    "fvcked": "fucked",
    "fvcking": "fucking",
    "nggr": "nigger",
    "p0rn": "porn",
    "pissin": "pissing",
    "r": "are",
    "u": "you",
    "ur": "your",
    "urself": "yourself",
    "wh0re": "whore",
    "wh0res": "whores",
}


_strings = [
    "abuse me",
    "abuse you",
    "anal",
    "anally",
    "anus",
    "ass fuck",
    "ass fucked",
    "ass fucker",
    "ass fucking",
    "ass-fuck",
    "ass-fucked",
    "ass-fucker",
    "ass-fucking",
    "assfuck",
    "assfucked",
    "assfucker",
    "assfucking",
    "ballsack",
    "beastial",
    "beastiality",
    "bellend",
    "bestiality",
    "bitch",
    "blow job",
    "blow jobs",
    "blowjob",
    "blowjobs",
    "breasts",
    "bukkake",
    "butt fuck",
    "butt fucked",
    "butt fucker",
    "butt fucking",
    "butt hole",
    "butt stuff",
    "butt-fuck",
    "butt-fucked",
    "butt-fucker",
    "butt-fucking",
    "butt-hole",
    "butthole",
    "buttstuff",
    "carpet muncher",
    "cawk",
    "cervix",
    "chink",
    "chinks",
    "clit",
    "clitoris",
    "coal burner",
    "coal burners",
    "coalburner",
    "coalburners",
    "cock sucker",
    "cock",
    "cock-sucker",
    "cockface",
    "cockhead",
    "cockmunch",
    "cockmuncher",
    "cocks",
    "cocksuck",
    "cocksucked",
    "cocksucker",
    "cocksucking",
    "coon",
    "coprophilia",
    "cum",
    "cumming",
    "cumms",
    "cummshot",
    "cums",
    "cumshot",
    "cunilingus",
    "cunillingus",
    "cunnilingus",
    "cunt",
    "cuntlick",
    "cuntlicker",
    "cuntlicking",
    "cunts",
    "cut me",
    "cut you",
    "dick",
    "dildo",
    "dildos",
    "dog-fucker",
    "doggin",
    "dogging",
    "dyke",
    "dykes",
    "e sex",
    "e-sex",
    "eat me out",
    "eat my ass",
    "eat you out",
    "eat your ass",
    "edging",
    "ejaculate",
    "ejaculated",
    "ejaculates",
    "ejaculating",
    "ejaculatings",
    "ejaculation",
    "ejakulate",
    "esex",
    "faggitt",
    "faggot",
    "faggots",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fatass",
    "felching",
    "fellate",
    "fellatio",
    "fingerfuck",
    "fingerfucked",
    "fingerfucker",
    "fingerfuckers",
    "fingerfucking",
    "fingerfucks",
    "fistfuck",
    "fistfucked",
    "fistfucker",
    "fistfuckers",
    "fistfucking",
    "fistfuckings",
    "fistfucks",
    "foot job",
    "footjob",
    "fuck you",
    "fuck your asshole",
    "fuck your brains out",
    "fuck your face",
    "fuck your mouth",
    "fuck your thighs",
    "fuck your tits",
    "fuck yourself",
    "fucking me",
    "fucking you",
    "gag me",
    "gag you",
    "gang bang",
    "gangbang",
    "gangbanged",
    "gangbangs",
    "gave me head",
    "gaysex",
    "gimme head",
    "give me head",
    "goatse",
    "golden shower",
    "gook",
    "gooks",
    "hand job",
    "hand-job",
    "handjob",
    "hang myself",
    "hang yourself",
    "hanged myself",
    "hanged yourself",
    "hanging myself",
    "hanging yourself",
    "heil",
    "hoe",
    "hoes",
    "horniest",
    "horny",
    "hotsex",
    "incest",
    "jack-off",
    "jackoff",
    "jerk off",
    "jerk-off",
    "jerked off",
    "jerking off",
    "jism",
    "jiz",
    "jizm",
    "jizz",
    "kike",
    "kikes",
    "kill my self",
    "kill myself",
    "kill your self",
    "kill yourself",
    "killed myself",
    "killed yourself",
    "killing myself",
    "killing yourself",
    "kms",
    "kys",
    "labia",
    "lick my",
    "lick your",
    "loli",
    "lolicon",
    "masterbate",
    "masterbation",
    "masterbations",
    "masturbate",
    "masturbated",
    "masturbates",
    "masturbating",
    "molest",
    "molestation",
    "molester",
    "molesting",
    "my nuts",
    "necrophilia",
    "nigga",
    "niggas",
    "nigger",
    "niggers",
    "nigs",
    "nutsack",
    "orgasim",
    "orgasims",
    "orgasm",
    "orgasms",
    "orgy",
    "paedo",
    "paedophile",
    "paraphilias",
    "pedo",
    "pedophile",
    "pedophilia",
    "pegging",
    "penis",
    "penisfucker",
    "phonesex",
    "pissflaps",
    "pissin",
    "pissing",
    "porn",
    "porno",
    "pornography",
    "pornos",
    "prostitute",
    "pussies",
    "pussy",
    "pussys",
    "rail you",
    "rape",
    "rapebait"
    "raped",
    "rapes",
    "raping",
    "rapist",
    "retard",
    "retardation",
    "retarded",
    "retards",
    "rim job",
    "rim-job",
    "rimjob",
    "rimming",
    "scrote",
    "scrotum",
    "semen",
    "sex",
    "shag",
    "shagging",
    "shemale",
    "shitdick",
    "shitfuck",
    "shota",
    "shotacon",
    "skank",
    "slut",
    "sluts",
    "smegma",
    "sodomize",
    "sodomy",
    "some head",
    "spic",
    "stabbing me",
    "stabbing you",
    "strangle me",
    "strangle you",
    "suicidal",
    "suicide",
    "testicle",
    "tie me",
    "tie you",
    "tit fuck",
    "tit fucked",
    "tit fucker",
    "tit fucking",
    "tit",
    "tit-fuck",
    "tit-fucked",
    "tit-fucker",
    "tit-fucking",
    "titfuck",
    "tits",
    "titties",
    "titty fuck",
    "titty fucked",
    "titty fucker",
    "titty fucking",
    "titty-fuck",
    "titty-fucked",
    "titty-fucker",
    "titty-fucking",
    "tittyfuck",
    "tittywank",
    "titwank",
    "tnd",
    "trannies",
    "tranny",
    "troon",
    "troons",
    "tug job",
    "tug-job",
    "tugjob",
    "use me",
    "use you",
    "vagina",
    "viagra",
    "vulva",
    "wank",
    "wanker",
    "whore",
    "whores",
    "wincest",
    "you will never be a woman",
    "you'll never be a woman",
    "your throat",
    "ywnbaw",
    "zoophilia",
]

_split_pattern = re.compile(r'[^\S\n\r]+')


_offensive_pattern = '|'.join(f'(\\b{re.escape(s)}\\b)' for s in _strings)


# Characters which were repeated more than once
_repeated_characters_pattern = re.compile(r'(.)\1+')


_offensive_matcher = re.compile(_offensive_pattern, re.IGNORECASE)


def _apply_normalization_map(haystack: str):
    for needle, replacement in _normalization_map.items():
        # Apparently compiled regexes are cached between invocations of
        # re.compile.
        pattern = re.compile(f"\\b{needle}\\b")

        haystack = pattern.sub(replacement, haystack)

    return haystack


def normalize_string(s: str):
    # Normalize the string to NFD (Normalization Form Decomposition) and Filter
    # out combining diacritical marks (e.g., accents)
    normalized_input = unicodedata.normalize('NFD', s)
    normalized_input = ''.join(
        char for char in normalized_input if not unicodedata.combining(char)
    )

    # Normalize whitespace
    normalized_input = ' '.join(_split_pattern.split(normalized_input))

    # Remove repeated characters
    normalized_input = _repeated_characters_pattern.sub(
        r'\1\1', normalized_input)

    # Replace slang
    normalized_input = _apply_normalization_map(normalized_input)

    return normalized_input


def is_offensive(s: str) -> bool:
    normalized_input = normalize_string(s)

    return bool(_offensive_matcher.search(normalized_input))
