from antiabuse.normalize import normalize_string

import re

_strings = [
    "1488",
    "beaner",
    "cervix",
    "chink",
    "chinks",
    "coal burner",
    "coal burners",
    "coalburner",
    "coalburners",
    "coon",
    "cunny",
    "cunny-pilled",
    "cunnypilled",
    "cut myself",
    "cut ourselves",
    "cut your self",
    "cut yourself",
    "cutmaxxer",
    "cvt your self",
    "cvt yourself",
    "dicked",
    "dicking",
    "edtwt",
    "faggot",
    "faggots",
    "groom me",
    "heil",
    "kike",
    "kikes",
    "kill my self",
    "kill myself",
    "kill your self",
    "kill yourself",
    "killed myself",
    "killed yourself",
    "killing myself",
    "killing yourself",
    "kms",
    "kys",
    "loli",
    "lolicon",
    "lolicons",
    "masturbate",
    "negress",
    "nigga",
    "niggas",
    "nigger",
    "niggerlicious",
    "niggers",
    "niglet",
    "niglets",
    "pajeet",
    "pajeets",
    "rape",
    "rapeable",
    "rapebait"
    "raped",
    "rapes",
    "raping",
    "rapist",
    "rapists",
    "self harm",
    "self-harm",
    "selfharm",
    "shit skin",
    "shitskin",
    "shota",
    "shotacon",
    "shotacons",
    "shtwt",
    "throat fuck",
    "throat fucking",
    "throat pussy",
    "throatfuck",
    "throatfucking",
    "tkd",
    "tnd",
    "trannies",
    "tranny",
    "trannys",
    "troon",
    "troons",
    "unrape",
    "unrapeable",
    "you will never be a woman",
    "you'll never be a woman",
    "ywnbaw",
]


_rude_pattern = '|'.join(f'(\\b{re.escape(s)}\\b)' for s in _strings)


_rude_matcher = re.compile(_rude_pattern, re.IGNORECASE)


def is_rude(s: str) -> bool:
    normalized_input = normalize_string(s)

    return bool(_rude_matcher.search(normalized_input))
