import re

blocked_words = [
    'anal',
    'anally',
    'arsehole',
    'aryan',
    'aryans',
    'ass fuck',
    'ass fucking',
    'ass hole',
    'ass',
    'assfuck',
    'assfucking',
    'asshole',
    'balls',
    'beaner',
    'bitch',
    'black people',
    'blood',
    'boob',
    'booba',
    'boobies',
    'boobies',
    'boobs',
    'boobs',
    'brown people',
    'bukkake',
    'chink',
    'chinks',
    'coal burner',
    'coal burners',
    'coalburner',
    'coalburners',
    'cock sucker',
    'cock suckers',
    'cock',
    'cocks',
    'cocksucker',
    'cocksuckers',
    'coon',
    'coons',
    'cotton picker',
    'cuck',
    'cucked',
    'cucking',
    'cuckold',
    'cuckolding',
    'cum',
    'cumming',
    'cunt',
    'cunts',
    'dead',
    'dick head',
    'dick heads',
    'dick',
    'dickhead',
    'dickheads',
    'dicks',
    'dike',
    'dikes',
    'dothead',
    'erotic',
    'fag',
    'faggots',
    'fagism',
    'fags',
    'fags',
    'feminazi',
    'foreskin',
    'foreskins',
    'fuck',
    'fucker',
    'fuckers',
    'fucking',
    'fucks',
    'gook',
    'gooks',
    'gun',
    'guns',
    'hitler',
    'hoe',
    'hoes',
    'hotwife',
    'kike',
    'kikes',
    'kill',
    'killed',
    'killer',
    'killing',
    'kys',
    'labia',
    'manlet',
    'manlets',
    'masturbate',
    'masturbating',
    'masturbation',
    'mudslime',
    'mudslimes',
    'naked',
    'neega',
    'neeger',
    'nig',
    'niggah',
    'niggress',
    'nigs',
    'orgasm',
    'orgasms',
    'paedo',
    'paedophile',
    'paedophiles',
    'pajeet',
    'pajeets',
    'paki',
    'pakkis',
    'pedo',
    'pedophile',
    'pedophiles',
    'penis',
    'penises',
    'piece of shit',
    'porn',
    'prostitute',
    'pussies',
    'pussy',
    'rag head',
    'rag heads',
    'raghead',
    'ragheads',
    'rape',
    'raped',
    'raping',
    'rapist',
    'roastie',
    'roasty',
    'scrotum',
    'scrotums',
    'seppo',
    'seppos',
    'sex',
    'shemale',
    'shemales',
    'skank',
    'skanks',
    'slave',
    'slut',
    'sluts',
    'spic',
    'suicide',
    'tard',
    'testicle',
    'testicles',
    'thicc',
    'tiddies',
    'tits',
    'titties',
    'towel head',
    'towel heads',
    'towelhead',
    'towelheads',
    'trannies',
    'tranny',
    'trannyism',
    'twat',
    'twats',
    'twink',
    'twinks',
    'urethra',
    'vagina',
    'virgin',
    'virginity',
    'vulva',
    'wank',
    'wanking',
    'wetback',
    'white people',
    'white trash',
    'whitey',
    'whore',
    'whores',
    'wog',
    'ywnbaw',
    'zionist',
    'zipperhead',
    'zipperheads',
]

blocked_strings = [
    'nigger',
    'cuckoldry',
]


assert not re.search(r'[^a-z ]', blocked_words)
assert not re.search(r'[^a-z ]', blocked_strings)

re_blocked_strings = '|'.join(blocked_strings)
re_blocked_words = '|'.join(f'\\b{w}\\b' for w in blocked_words)
re_blocked = re.compile(
    f'({re_blocked_strings})|({re_blocked_words})',
    re.IGNORECASE
)
