on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: ./mypy.sh

  functionality-tests-1:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Run functionality tests
        run: ./test/util/with-container.sh ./test/functionality.sh 1
        env:
          DUO_EMAIL_KEY: 'not-a-real-key'
          DUO_EMAIL_URL: 'https://example.com'

          DUO_R2_BUCKET_NAME: s3-mock-bucket
          DUO_R2_ACCT_ID: unused-in-dev-env
          DUO_R2_ACCESS_KEY_ID: s3-mock-access-key-id
          DUO_R2_ACCESS_KEY_SECRET: s3-mock-secret-access-key-secret

  functionality-tests-2:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Run functionality tests
        run: ./test/util/with-container.sh ./test/functionality.sh 2
        env:
          DUO_EMAIL_KEY: 'not-a-real-key'
          DUO_EMAIL_URL: 'https://example.com'

          DUO_R2_BUCKET_NAME: s3-mock-bucket
          DUO_R2_ACCT_ID: unused-in-dev-env
          DUO_R2_ACCESS_KEY_ID: s3-mock-access-key-id
          DUO_R2_ACCESS_KEY_SECRET: s3-mock-secret-access-key-secret

          DUO_CRON_PHOTO_CLEANER_DRY_RUN: 'true'
          DUO_CRON_AUDIO_CLEANER_DRY_RUN: 'true'

  functionality-tests-3:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Run functionality tests
        run: ./test/util/with-container.sh ./test/functionality.sh 3
        env:
          DUO_EMAIL_KEY: 'not-a-real-key'
          DUO_EMAIL_URL: 'https://example.com'

          DUO_R2_BUCKET_NAME: s3-mock-bucket
          DUO_R2_ACCT_ID: unused-in-dev-env
          DUO_R2_ACCESS_KEY_ID: s3-mock-access-key-id
          DUO_R2_ACCESS_KEY_SECRET: s3-mock-secret-access-key-secret

  functionality-tests-4:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Run functionality tests
        run: ./test/util/with-container.sh ./test/functionality.sh 4
        env:
          DUO_EMAIL_KEY: 'not-a-real-key'
          DUO_EMAIL_URL: 'https://example.com'

          DUO_R2_BUCKET_NAME: s3-mock-bucket
          DUO_R2_ACCT_ID: unused-in-dev-env
          DUO_R2_ACCESS_KEY_ID: s3-mock-access-key-id
          DUO_R2_ACCESS_KEY_SECRET: s3-mock-secret-access-key-secret

  functionality-tests-5:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Run functionality tests
        run: ./test/util/with-container.sh ./test/functionality.sh 5
        env:
          DUO_EMAIL_KEY: 'not-a-real-key'
          DUO_EMAIL_URL: 'https://example.com'

          DUO_R2_BUCKET_NAME: s3-mock-bucket
          DUO_R2_ACCT_ID: unused-in-dev-env
          DUO_R2_ACCESS_KEY_ID: s3-mock-access-key-id
          DUO_R2_ACCESS_KEY_SECRET: s3-mock-secret-access-key-secret

  functionality-tests-6:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Run functionality tests
        run: ./test/util/with-container.sh ./test/functionality.sh 6
        env:
          DUO_EMAIL_KEY: 'not-a-real-key'
          DUO_EMAIL_URL: 'https://example.com'

          DUO_R2_BUCKET_NAME: s3-mock-bucket
          DUO_R2_ACCT_ID: unused-in-dev-env
          DUO_R2_ACCESS_KEY_ID: s3-mock-access-key-id
          DUO_R2_ACCESS_KEY_SECRET: s3-mock-secret-access-key-secret

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: ./test/util/with-container.sh ./test/unit/unit.sh --no-sudo
        env:
          DUO_EMAIL_KEY: 'not-a-real-key'
          DUO_EMAIL_URL: 'https://example.com'

          DUO_R2_BUCKET_NAME: s3-mock-bucket
          DUO_R2_ACCT_ID: unused-in-dev-env
          DUO_R2_ACCESS_KEY_ID: s3-mock-access-key-id
          DUO_R2_ACCESS_KEY_SECRET: s3-mock-secret-access-key-secret
